### ISSUE TITLE
Decouple Kweb from embedded server

### ISSUE THREAD

**Issue by wooky** [kwebio/kweb-core#100]
I want to run Kweb on a servlet rather than as a standalone server. My motivation for this is for easy deployment by creating a WAR file. However, while I can easily do it in Ktor, I can't in Kweb because the Kweb class forces me to create an embeddedServer. It would be nice if I had the option of using the module directly.

**Comment by sanity** [comment]
Related: #58

**Comment by sanity** [comment]
cc: @alkoclick

**Comment by alkoclick** [comment]
I was considering making the entire server config optional and passable as an argument. 

@sanity What direction do you want Kweb to take? Opinionated strong defaults, or customizable configs?

**Comment by wooky** [comment]
Maybe make it a feature, so I can do something like
```kotlin

Install(Kweb) {
    doc.body.new {
        ...
    }
}
```

This way the user has full control over their server.

**Comment by sanity** [comment]
@alkoclick My hope is to take a layered approach, so sensible defaults but flexibility for those that need it.

Per @wooky's suggestion, if we could break up the Kweb class such that Kweb can be attached to an existing Ktor instance - that would increase flexibility a lot.

However, I still think we should retain the current high-level interface (perhaps as a wrapper around this) that doesn't require dealing directly with Ktor.

I haven't looked too closely at the `Install()` mechanism in Ktor yet so not sure what its capabilities are, but that looks like an interesting direction.

**Comment by sanity** [comment]
Relevant: https://ktor.io/advanced/features

**Comment by wooky** [comment]
Here's what the feature can look after a minimum amount of refactoring:
https://gist.github.com/wooky/ca0564c3f12a288c4a362740b558c810

The most important things here are:
 - The addition of the Feature companion object
 - Extracting everything from this.module in createServer() into the method called setup(), which accepts an Application

`install()`ing it in a standard Ktor application makes it work seamlessly.

**Comment by sanity** [comment]
@wooky Very nice, is that code working?

**Comment by wooky** [comment]
Yes, I'm using it in my test application with no problems.

**Comment by sanity** [comment]
That's great, if you wouldn't mind sending a pull request I can release a new version with this improvement.

One thing to note is that we're trying to move functionality out of the `Kweb` class due to #58, so if this provides a natural way to do that we should.

**Comment by wooky** [comment]
I have no problem making a pull request for this. My only concern is that this will definitely break existing code. I have a couple opinions about it:
1. Accept that this change will break existing applications
2. Make Kweb a "hybrid" class for now - you can either instantiate it as before, or you can `install()` it to an existing Ktor app

And, of course, the documentation will need to be updated correspondingly.

**Comment by sanity** [comment]
Oh, I didn't realize that it would significantly change the current API - I think it's important that something like this still works:

```kotlin
fun main() {
  Kweb(port = 16097) {
    doc.body.new {
      h1().text("Hello World!")
    }
 }
}
```

So I think that would suggest option 2 - allowing Kweb to be instantiated independently as it currently can, or allowing it to be attached to an existing Ktor instance.

**Comment by wooky** [comment]
OK, good to know. I'll prepare a pull request within the week.
