### ISSUE TITLE
How to run kweb application on Google App Engine

### ISSUE THREAD

**Issue by heathwinning** [kwebio/kweb-core#103]
I am attempting to deploy the basic Kweb hello world on GAE, but I have been unsuccessful.
```kotlin
// HelloWorld.kt

fun main() {
  Kweb(port = 16097) {
    doc.body.new {
      h1().text("Hello World!")
    }
  }
}
```
I am unfamiliar with the Java ecosystem on GAE (it's very different to the python setup I'm used to!) and I also have zero understanding of the relationship between Ktor and Kweb.

I have attempted to use the [java deployment descriptor](https://cloud.google.com/appengine/docs/standard/java/config/webxml) with the `web.xml`
```xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         version="3.0">
    <servlet>
        <servlet-name>Kweb</servlet-name>
        <servlet-class>com.example.HelloWorldKt</servlet-class>  // this is wrong
    </servlet>

    <servlet-mapping>
        <servlet-name>Kweb</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>
</web-app>
```
which gives me the error `Servlet class com.example.HelloWorldKt is not a javax.servlet.Servlet`. I don't dispute that `HelloWorldKt` is not a `Servlet`, but I'm unsure how I should arrange things to direct the wrong line to the (Ktor? Jetty?) servlet from the Kweb instance. How should I be doing this?

---

Another setup I tried was to embed the Kweb app in a Ktor app via [Can Kweb be embedded in an existing Ktor app? demo](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/io/kweb/demos/feature/FeatureApp.kt)
```kotlin
fun Application.main() {
    embeddedServer(Jetty, module = Application::kwebFeature).start()
}

private fun Application.kwebFeature() {
    ...
    install(Kweb) {
        buildPage = {
            ...
        }
    }
}
```
and then follow [Run a Kotlin Ktor app on App Engine (https://cloud.google.com/community/tutorials/kotlin-ktor-app-engine-java8).
```
// resources/application.conf

ktor {
    application {
        modules = [ com.example.demo.HelloWorldKt.main ]
    }
}
```
```xml
// web.xml

<?xml version="1.0" encoding="ISO-8859-1" ?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" version="3.0">
    <servlet>
        <display-name>KtorServlet</display-name>
        <servlet-name>KtorServlet</servlet-name>
        <servlet-class>io.ktor.server.servlet.ServletApplicationEngine</servlet-class>
        <!-- path to application.conf file, required -->
        <init-param>
            <param-name>io.ktor.config</param-name>
            <param-value>application.conf</param-value>
        </init-param>
    </servlet>
    <servlet-mapping>
        <servlet-name>KtorServlet</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>
</web-app>
```
 But this seemed to run a server behind a server in my local app engine environment - one request would return "Page not found" and launch the Kweb server, and subsequent requests went to Kweb - and I couldn't even get this behaviour when deployed.

---

P.S. Kweb is awesome! I have so often been frustrated by the need to orchestrate HTML, CSS, JS, and server, and Kweb is going to make me so much more motivated to complete projects because it is far less prone to becoming a teetering tower of clean-this-up-later.

**Comment by sanity** [comment]
Kweb uses Ktor to handle HTTP and WebSocket transport, while Kweb handles everything on top of that (DOM manipulation, events, etc).

Using Kweb on GAE is something I've considered, in theory, now that Kweb can be attached to an existing Ktor instance, and I believe Ktor can run on GAE, it should be doable.  I also believe GAE supports WebSockets which Kweb relies on.

One suggestion might be to get Ktor working on GAE as a first step - perhaps just returning a trivial text document.  From there you could try attaching Kweb to the Ktor instance.

@wooky Built the Ktor feature stuff so he may have some suggestions.

> P.S. Kweb is awesome! I have so often been frustrated by the need to orchestrate HTML, CSS, JS, and server, and Kweb is going to make me so much more motivated to complete projects because it is far less prone to becoming a teetering tower of clean-this-up-later.

Thank you!

**Comment by wooky** [comment]
I haven't yet tried to run a Kweb application as a servlet, but I see a few issues with your config files.

Don't start an embedded Jetty server from Application.main(), but from main(). It's for this reason you're having a server start from another server. And, realistically, you don't even need that - I only included the main method as a way of testing the server.

In order to get the Ktor server run a servlet, make the Application.kwebFeature method public, and in application.conf, set modules to [ com.example.demo.HelloWorldKt.kwebFeature ]. Now it should run properly.

Also, in web.xml, I'm not sure if the <init-param> is in the right place. According to [Ktor's WAR page](https://ktor.io/servers/deploy/packing/war.html), you'll need to place the tag outside <servlet> and rename it to <context-param>.

**Comment by heathwinning** [comment]
> I also believe GAE supports WebSockets which Kweb relies on.

This is true in the flexible environment, but not in the standard environment, as I have found.

> One suggestion might be to get Ktor working on GAE as a first step - perhaps just returning a trivial text document. From there you could try attaching Kweb to the Ktor instance.

@sanity this was a good suggestion, I managed to get [ktor working on GAE flexible](https://github.com/heathwinning/ktor-gae-flex)

> In order to get the Ktor server run a servlet, make the Application.kwebFeature method public, and in application.conf, set modules to [ com.example.demo.HelloWorldKt.kwebFeature ]. Now it should run properly.

@wooky thanks for this, it did at least let me deploy [Kweb on GAE](https://github.com/heathwinning/kweb-gae-flex), but the websocket functionality did not to play nice.

```
(index):117 WebSocket connection to 'ws://[project-id].appspot.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 501
```
followed by
```
(index):159 WebSocket error 
Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
isTrusted: true
type: "error"
target: WebSocket {url: "ws://[project-id].appspot.com/ws", readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
currentTarget: WebSocket {url: "ws://[project-id].appspot.com/ws", readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
eventPhase: 0
bubbles: false
cancelable: false
defaultPrevented: false
composed: false
timeStamp: 1853.705000001355
srcElement: WebSocket {url: "ws://[project-id].appspot.com/ws", readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
returnValue: true
cancelBubble: false
path: []
__proto__: Event

WebSocket was closed without a reason specified
```
then page reload and repeat.

---

I wanted to try the [Web Socket Example](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/websocket-jetty#app-engine-flexible-environment---web-socket-example) from google to see that the websockets requests were working, but I was unable to compile/deploy it.

---

I don't have a question or any suggestion of direction to continue this thread, but I'm willing to try any ideas you might have.

I intend use Compute Engine VMs to deploy my app instead.

**Comment by wooky** [comment]
I've had an issue the other trying to deploy a Kweb app as a servlet on Jetty, also having the page constantly reload. Maybe there's some similar issue here as well. Check the Java logs if you have any.

**Comment by sanity** [comment]
@heathwinning  I agree with @wooky, if you have access to the log output of the app it could offer some useful clues.  Further diagnosis would probably require creating a simple app that just tested Ktor's websocket functionality.

> I intend use Compute Engine VMs to deploy my app instead.

 While it would be great for Kweb to work with GAE, the Compute Engine option might be more prudent at this stage, as it will be more flexible.

**Comment by sanity** [comment]
@heathwinning Did you have any luck with this?

**Comment by heathwinning** [comment]
In short, no. I intended to go back to GAE to generate logs after deploying on GCE, but that was also unsuccessful in a different way.

I will return to this issue when I have some time.

**Comment by heathwinning** [comment]
Sorry for the long delays. I have abandoned this issue after realising that I can deploy to GAE with docker, which works! I have made a [sample repository](https://github.com/heathwinning/kweb-gae-docker) with a working Kweb+Docker+GAE setup.

**Comment by sanity** [comment]
@heathwinning Nice!  Would you mind if I linked your sample repository from the FAQ in the user manual?  I think this could be useful to others.

**Comment by heathwinning** [comment]
I don't mind at all, please do.
