### ISSUE TITLE
Routing somewhat broken behind reverse proxy

### ISSUE THREAD

**Issue by wooky** [kwebio/kweb-core#104]
My Kweb server is running as a servlet on http://localhost:12345/myapp, and it's hidden behind an nginx reverse proxy such that you can access it through https://example.com. There are a couple issues arising.

When I navigate to https://example.com, I'm greeted with an error `Not Found: /myapp/`. Whether it's something I need to configure on nginx or server settings, I don't know yet.

More importantly, when navigating, the URL does not get updated. In the server logs, as well as the web page's error console, this message appears:
```
Error evaluating [history.pushState({}, "", "http://localhost:12345/some/other/page");] : SecurityError: The operation is insecure.
```
It looks like the server calls pushState including the domain name. I _believe_ this could be solved with a proper nginx config, but I fail to see why the server would put the domain name there in the first place.

**Comment by sanity** [comment]
Hmm, wondering if this could be related to https://github.com/kwebio/kweb-core/pull/92, cc: @alkoclick

**Comment by wooky** [comment]
I figured out that in WebBrowser::pushState, instead of setting the url to URL.parse(path), we can set to URL.parse(path).path(). This way the query parameters should be preserved without having to tack on the domain.

No idea yet how to fix the first issue, though.

**Comment by alkoclick** [comment]
I don't think it is related #92 @sanity, but I'm not too certain either. I actually encountered the same problem a couple days ago and I have a hack in place, which is roughly:

```kotlin
fun WebBrowser.updateQueryParams(params: Parameters) {
    url.apply {
        val parsed = URL.parse(value)
        value = parsed
            .withScheme((if (prod) Scheme.https else Scheme.http).toString())
            .withQuery(params.formUrlEncode())
            .toString()
            .let { if (prod) it.replace(Regex(":\\d+"), "") else it }
    }
}
```

Another problem here is that the Kvar chain in WebBrowser doesn't track schemes. Relative may be the way to go, as @wooky has started

**Comment by alkoclick** [comment]
Btw, behind reverse proxy you seem to also be losing some of the websockets functionality. I was on a Kubernetes NodePort directly to my pods until a few days ago and when I killed a pod, it restarted and sent a client refresh. Now that it's behind the proxy, that is no longer the case

**Comment by alkoclick** [comment]
This PR has actually broken the fixes introduced in #92 (query parameter behaviour)

https://github.com/kwebio/kweb-core/commit/a7150012f4bbc3360a1572643ae932573557afdd

**Comment by sanity** [comment]
Crap, is the proper solution here that we need to push the path, query, and fragment (if the latter two are present) - rather than just the path?

**Comment by alkoclick** [comment]
Probably yes. I wanted to take a more detailed look but I'm currently buried in work, so I rolled back to 0.5.17 :/

**Comment by sanity** [comment]
Let me see what I can do.

**Comment by sanity** [comment]
@alkoclick When you get a chance, can you see if `0.6.1` solves the problem?

**Comment by sanity** [comment]
@wooky Hopefully it won't break your use-case either, it shouldn't.

**Comment by alkoclick** [comment]
So, finally got to version bump our Kweb, and trying this out. Resolves properly behind the reverse proxy, but the current relative behavior means that the following code block (which used to be what we had before these changes and I dream of returning to) is no longer valid:

```kotlin
fun WebBrowser.updateQueryParams(params: Parameters) {
    url(simpleUrlParser).query.value = params.formUrlEncode()
}
```

API wise I think this is ideal - it allows a user to only edit a part as necessary. However, this is not working in the code and is very hard to get working that way with the current functionality. I think my suggestion was wrong, we shouldn't be treating the path, query params and fragment, however we should support partial updates. As such I think the best idea is to close this and tackle this in another issue - this one has been resolved.

**Comment by alkoclick** [comment]
Note that this is resolved as far as I'm concerned - got any updates @wooky ?

**Comment by sanity** [comment]
Closing this for now.
