### ISSUE TITLE
how to layout parameters

### ISSUE THREAD

**Issue by guibbv2011** [kwebio/kweb-core#106]
Hi Ian Clarke, at first glance I liked the kweb, but I have difficulties, size of the widget eg: (fomantics.ui.container: height = x, width = y), image, drawable color, padding, margin, mainAxisAligment, crossAxisAligment, is a matter of knowing the position and size of the widgets, and also have some hot heload mode?

**Comment by sanity** [comment]
I'm afraid I'm not clear on your first question, but with respect to hot reload, Kweb has supported this in the past although it isn't currently supported.  It could be supported again with a small amount of development effort.

**Comment by sanity** [comment]
Closing, please reopen if you'd like to continue the discussion.
