### ISSUE TITLE
ToDo demo is including Jquery at a non-existent URL

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#107]
Something in the Todo demo is trying to access the URL `http://demo.kweb.io:7659/lists/kweb_native_assets/jquery/jquery-3.1.1.min.js` for some reason, which doesn't exist.  Could be indicative of something more serious.

**Comment by rpanic** [comment]
Well, this is defenitely connected to the StaticFilePlugin. I thought this would work by now, also since you confirmed it working correctly. I try to look at it as soon as possible

**Comment by sanity** [comment]
https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/io/kweb/plugins/jqueryCore/JQueryCorePlugin.kt#L17:

Should:

```kotlin
                .attr("src", "$resourceRoute/jquery-3.1.1.min.js")
```

be:

```kotlin
                .attr("src", "/$resourceRoute/jquery-3.1.1.min.js")
```

?

**Comment by sanity** [comment]
(Note that the plugin mechanism now configures the HTML page using JSoup, which is a big improvement).

**Comment by sanity** [comment]
Was a simple fix, just a missing `/`.
