### ISSUE TITLE
Allow editing parts of the URL

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#111]
Related issues: #91 #92  #104

Tl;dr: There is currently no way to edit path params and query params after they have been added to the URL once

The flow with the automatic push state is nice, but as long as it only uses the last url value, it cannot properly understand which parts need changing. Either there should be a delta between the previous and new value to determine what to update, or there should be linked kvars exposing parts of the url for updating (I think I noticed this somewhere, dunno if it's still around)

**Comment by alkoclick** [comment]
Hmmmm, took another stab at it this morning and the following works:

```kotlin
fun WebBrowser.updateQueryParams(params: Parameters) {
    url.apply {
        value = URL.parse(value).withQuery(params.formUrlEncode()).toString()
    }
}
```

**Comment by sanity** [comment]
> There is currently no way to edit path params and query params after they have been added to the URL once

I'm not clear on what you mean by this, could you give a example in context?

**Comment by alkoclick** [comment]
Sorry for the un-clarity, it's been kinda that way for me as well, since some solutions worked and some didn't. My issue was about changing the url with (I think) `browser.pushState` and I was getting something like

`url?query=value`

Attempt to navigate to `url?query=value2`

`url?query=value&query=value2`

This issue may be closeable due to not enough info tbh, I figured out what works (see above), not sure why, but after that I haven't invested any additional effort into tracking it down

**Comment by sanity** [comment]
I believe this should now be fixed as of a few versions ago.
