### ISSUE TITLE
how to compile kweb project?

### ISSUE THREAD

**Issue by t0in4** [kwebio/kweb-core#112]
Hello,
how to create kweb project in ide (intellij or android studio)?
Or if i prefer to create kweb project without ide only with vim - so, how to compile it from terminal?
Looking forward for cooperation,
Best regards
error:
Build file '/home/123424/kweb2/build.gradle' line: 10
A problem occurred evaluating root project 'kweb2'.
> Could not find method compile() for arguments [com.github.kwebio:kweb-core:0.6.5] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by sanity** [comment]
Hi, you should create a Kotlin project using Gradle, you can find instructions [here](https://kotlinlang.org/docs/reference/using-gradle.html), and then add Kweb as a dependency to the `build.gradle` file as described [here](http://docs.kweb.io/en/latest/gettingstarted.html#adding-kweb-to-your-project).

**Comment by t0in4** [comment]
Thank you for answer, but could you please write step by step. 
i try to follow instructions but still drowning in errors 
 What went wrong:
Script compilation errors:

  Line 10:           maven{ url 'https://jitpack.io'}
                                ^ Unexpected tokens (use ';' to separate expressions on the same line)

  Line 15:          compile 'com.github.kwebio:kweb-core:0.6.5'
                            ^ Unexpected tokens (use ';' to separate expressions on the same line)

  Line 16:          compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.30'
                                 ^ Expecting an element

  Line 16:          compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.30'
                                   ^ Unexpected tokens (use ';' to separate expressions on the same line)

  Line 20:     kotlin{"jvm") version "1.3.71"
                           ^ Unexpected tokens (use ';' to separate expressions on the same line)

  Line 21:     }
                ^ Expecting '}'

  Line 07:  buildScript {
            ^ Unresolved reference: buildScript

  Line 14:          classpath(kotlin("gradle-plugin",version="1.3.71"))
                    ^ Unresolved reference: classpath

  Line 15:          compile 'com.github.kwebio:kweb-core:0.6.5'
                    ^ Unresolved reference: compile

  Line 16:          compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.30'
                    ^ Unresolved reference: compile
**My build.gradle.kts file:**
 2  * This file was generated by the Gradle 'init' task.
  3  *
  4  * This is a general purpose Gradle build.
  5  * Learn how to create Gradle builds at https://guides.gradle.org/creating-n    ew-gradle-builds
  6  */
  7  buildScript {
  8      repositories {
  9           mavenCentral()
 10           maven{ url 'https://jitpack.io'}
 11           jcenter()
 12           }
 13      dependencies {
 14          classpath(kotlin("gradle-plugin",version="1.3.71"))
 15          compile 'com.github.kwebio:kweb-core:0.6.5'
 16          compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.30'
 17      }
 18 }
 19 plugins {
 20     kotlin{"jvm") version "1.3.71"
 21     }
**My directory tree**
.
├── build.gradle.kts
├── errors.txt
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
├── helloworld.kt
└── settings.gradle.kts

**Comment by t0in4** [comment]
It compiled by commad $ ./gradlew install
but when i try to compile kotlin file it have a bunch of errors
$ kotlinc helloworld.kt -d hello.jar
import kweb.*
       ^
helloworld.kt:2:8: error: unresolved reference: kweb
import kweb.dom.element.*
       ^
helloworld.kt:3:8: error: unresolved reference: kweb
import kweb.dom.element.creation.tags.*
       ^
helloworld.kt:6:5: error: unresolved reference: Kweb
    Kweb(port=16097){
    ^
helloworld.kt:7:5: error: unresolved reference: doc
    doc.body.new {
    ^
helloworld.kt:8:5: error: unresolved reference: h1
    h1().text("Hello World")

**Comment by t0in4** [comment]
Please, could you write in "Getting started" build instructions step by step

**Comment by sanity** [comment]
Hi, the problems you're having appear to be with your Kotlin and/or Gradle setup, rather than anything Kweb specific.  

Have you been able to successfully create a simple "hello world" Kotlin program built using Gradle (without Kweb)?  If not, I suggest you start by doing that, you can get help [here](https://www.reddit.com/r/Kotlin/).

**Comment by t0in4** [comment]
Hello, 
i can build kotlin simple programs by 
$kotlinc file.kt -include-runtime -d file.jar
and run them by
$java -jar file.jar
like so, it is working.
but when i tried to compile helloworld.kt (with Kweb) raised errors;
$ kotlinc helloworld.kt -include-runtime -d helloworld.jar
helloworld.kt:1:8: error: unresolved reference: kweb
import kweb.*
       ^
helloworld.kt:2:8: error: unresolved reference: kweb
import kweb.dom.element.*
       ^
helloworld.kt:3:8: error: unresolved reference: kweb
import kweb.dom.element.creation.tags.*
       ^
helloworld.kt:6:5: error: unresolved reference: Kweb
    Kweb(port=16097){
    ^
helloworld.kt:7:5: error: unresolved reference: doc
    doc.body.new {
    ^
helloworld.kt:8:5: error: unresolved reference: h1
    h1().text("Hello World")

**Comment by sanity** [comment]
Ah, I think I see the problem, you should use `gradle` to compile your code, rather than `kotlinc`, eg:
```
gradle build
```
[This](https://kotlinlang.org/docs/reference/using-gradle.html) documentation may be helpful.

**Comment by t0in4** [comment]
ok, but i build it just now in intellij ide. 
1. choose create "New Project" > Gradle > Kotlin(JVM)
2. choose in project tree - build.gradle ( [my build.gradle](https://pastebin.fun/w3e3O7dxRP))
    add what needed in Kweb "Getting Started" chapter
    2.1. don't forget to buildDependents (in tab Gradle (right side of screen)). Expand "Tasks" 
          folder and then "build" folder. Double click to "buildDependents"
3. then step to "src" directory
── src
    ├── main
    │   ├── java
    │   ├── **kotlin** //choose kotlin directory and create kotlin file "helloworld.kt"
    │   │   └── helloworld.kt
4. when you add all needful stuff in helloworld.kt. Look to word "kweb" if word is red, so you need 
    to run again buildDependents. If word "kweb" is still red try to build project, or just click to 
    "build" everywhere where you see it.
5. when "kweb" word in helloworld.kt is come to grey color, you can click right button on 
    helloworld.kt file and run it
6. Voila! In browser you can go to - localhost:16097 and vying **Hello World!**

**Comment by sanity** [comment]
Ah, so it's working now?

**Comment by sanity** [comment]
Closing, please reopen if this issue isn't resolved.
