### ISSUE TITLE
could kweb app be an application for android?

### ISSUE THREAD

**Issue by t0in4** [kwebio/kweb-core#113]
Hello, i mean - can i launch kweb compiled app in android? And would it work all in one?

**Comment by sanity** [comment]
Hi, this seems like it should be possible in theory as there are examples of [Ktor](https://diamantidis.github.io/2019/11/10/running-an-http-server-on-an-android-app) running as a HTTP server on Android and Kweb runs on Ktor, although I'm not aware that anyone has tried it yet.

[This](http://docs.kweb.io/en/latest/faq.html#can-kweb-be-embedded-in-an-existing-ktor-app) explains how to connect Kweb to an existing Ktor instance.

**Comment by ethanmdavidson** [comment]
I've built a [demo app](https://github.com/kwebio/kweb-demos/tree/master/android) that runs Kweb in an android app. Shoebox doesn't work on android; the issue looks trivial but I didn't look into it at all.

@sanity I've created a kweb-demos repo, and put the demo in a subfolder. I think for #114 the other demos from kweb-core can also be moved here. Does this make sense, or should there be a separate repo for each demo?

**Comment by sanity** [comment]
@ethanmdavidson I haven't verified that it works, but I've attempted to fix that issue with Shoebox in version `0.3.1` by renaming the function name that contained spaces.

**Comment by ethanmdavidson** [comment]
yep, it works with that version of shoebox

**Comment by sanity** [comment]
@ethanmdavidson Nice!  Would you mind updating the "Shoebox must be excluded because it will prevent the app from building" from the index.md of the demo repo?

**Comment by ethanmdavidson** [comment]
well, I didn't want the demo to be in a broken state so I was planning on taking that out once a new version of kweb is released with updated shoebox dependency

**Comment by sanity** [comment]
Ah, doh - good point.  Will do that now

**Comment by sanity** [comment]
@ethanmdavidson Kweb `0.7.5` should use the latest version of Shoebox.

**Comment by ethanmdavidson** [comment]
okay, I've updated the demo and the readme. I still can't get over how simple this was!
