### ISSUE TITLE
to create a standalone TODO or demo app

### ISSUE THREAD

**Issue by smallufo** [kwebio/kweb-core#114]
I cannot find docs about how to run TODO app.
It seems demos are not a separated artifact.
I suggest migrate kweb-core/src/main/kotlin/kweb/demos to standalone artifact.
So that we can easily clone/build/run it.

Thanks.

**Comment by sanity** [comment]
This is a good idea, shouldn't be too difficult.

**Comment by sanity** [comment]
Thanks to @ethanmdavidson you can now find this and other demos in this repository: https://github.com/kwebio/kweb-demos

**Comment by ethanmdavidson** [comment]
There is also a template repo at https://github.com/kwebio/kweb-template

**Comment by alkoclick** [comment]
Closing as this appears done
