### ISSUE TITLE
Add preventDefault() ability while handling events

### ISSUE THREAD

**Issue by marad** [kwebio/kweb-core#115]
Hi I'm experimenting a bit with KWeb on my side project and I'd like to create custom keyboard shortcuts, but unfortunately on Ctrl+P there is browser print function. 

I did this:
```kotlin
doc.body.on.keyup {
  if (it.ctrlKey && it.key == "p") {
    println("ctrl+p pressed")
  }
}
```

The message is shown, but also browser print dialog pops up.

**Comment by marad** [comment]
For now I kinda hacked around with custom events. I just register regular JS shortcut with  Mousetrap which sends my action event:

```javascript
Mousetrap.bind('ctrl+p', function(e) {
    var event = new CustomEvent('searchPageAction');
    document.dispatchEvent(event);
    e.preventDefault()
});
```

Then in KWeb I can catch that and do what needs to be done. The best part of coming up with this is that I can actually use `onImmediate` to show the dialog without a lag (which would not be an option with preventDefault on server):

```
doc.body.onImmediate.event("searchPageAction") {
  // show search dialog
}

doc.body.on.event("searchPageAction") {
  // do things that should be done on the server (if any)
}
```

**Comment by marad** [comment]
Actually  I've made a little plugin for that:

```kotlin
import kweb.WebBrowser
import kweb.plugins.KwebPlugin
import org.jsoup.nodes.Document

class MousetrapPlugin : KwebPlugin() {
    override fun decorate(doc: Document) {
        doc.head().appendElement("script")
            .attr("src", "//cdnjs.cloudflare.com/ajax/libs/mousetrap/1.4.6/mousetrap.min.js")
    }
}

internal fun WebBrowser.registerShortcutForAction(shortcut: String, action: String) {
    evaluate(
        """
            Mousetrap.bind("$shortcut", function() {
              var event = new CustomEvent("$action");
              document.body.dispatchEvent(event);
              return false;
            });
        """.trimIndent()
    )
}
```

**Comment by sanity** [comment]
Very cool, just trying to figure out what the most general version of this is.

Is the main need here the ability to call [preventDefault()](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) from within the event handler on the client before the event is reported to the server?

Could this be achieved with something like:

```kotlin
element.on(preventDefault = true).click {
  println("Element clicked")
}
```
?

**Comment by marad** [comment]
@sanity I guess it depends on what the user wants to achieve. In my case that would totally work, but I can imagine that someone would want to cancel an event based on some data from within the event.

**Comment by sanity** [comment]
Yes, that's a possibility - although hopefully a rare use-case in practice.

**Comment by marad** [comment]
I've to little experience with frontend development to tell. It's your call :)

**Comment by sanity** [comment]
Not sure if this is still relevant.

**Comment by sanity** [comment]
Apparently fixed 7/17/2021
