### ISSUE TITLE
To externalize JS code to separated JS file

### ISSUE THREAD

**Issue by smallufo** [kwebio/kweb-core#118]
To externalize JS code to separated JS file , instead of put it in the <head><script> block of each page.
Maybe lazy loading JS file will also increase the load time.

Thank you.

**Comment by sanity** [comment]
Are you referring to the generated JavaScript?

That would definitely be neater than embedding it in `<script>` tags, but I'm concerned that it would slow down initial page render due to the additional HTTP get request.

**Comment by smallufo** [comment]
Yes , I meant the generated JS. I just run some demo and saw the source containing these JS in the header . I think it is not good for pagespeed . Modern approaches may externalize these JS codes to a js file (and adding some md5 signature to the filename) . And it may be cached too .

**Comment by sanity** [comment]
It wouldn't be too difficult to implement - and it would be tidier, but I'm not convinced it would reduce page-render time.  It would be worth experimenting with though.

**Comment by sanity** [comment]
I think this is still relevant.

Related: #332

**Comment by sanity** [comment]
Thinking about it, I'm not sure this would be advantageous.
