### ISSUE TITLE
url(simpleUrlParser) is broken

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#122]
Again, I may be misdirected here somehow, but seeing the new `WebBrowser.url` I wanted to try it out in the following way (which used to work)

`url(simpleUrlParser)`

The way I understand this, this should also allow me to access the the extensions such as query, path, etc. However, this throws immediately as the scheme is missing

Adding the above line to the FeatureApp, produces the following:
```
io.mola.galimatias.GalimatiasParseException: Missing scheme
	at io.mola.galimatias.GalimatiasParseException$Builder.build(GalimatiasParseException.java:103)
	at io.mola.galimatias.URLParser.handleFatalMissingSchemeError(URLParser.java:173)
	at io.mola.galimatias.URLParser.parse(URLParser.java:387)
	at io.mola.galimatias.URL.parse(URL.java:307)
	at kweb.PreludeKt$simpleUrlParser$1.invoke(prelude.kt:420)
	at kweb.PreludeKt$simpleUrlParser$1.invoke(prelude.kt:419)
	at kweb.state.KVar.map(KVar.kt:30)
	at kweb.WebBrowser.url(WebBrowser.kt:123)
	at kweb.demos.feature.FeatureAppKt$kwebFeature$2$1$1.invoke(FeatureApp.kt:31)
	at kweb.demos.feature.FeatureAppKt$kwebFeature$2$1$1.invoke(FeatureApp.kt)
	at kweb.ElementKt.new(Element.kt:386)
	at kweb.ElementKt.new$default(Element.kt:383)
	at kweb.demos.feature.FeatureAppKt$kwebFeature$2$1.invoke(FeatureApp.kt:30)
	at kweb.demos.feature.FeatureAppKt$kwebFeature$2$1.invoke(FeatureApp.kt)
	at kweb.Kweb$listenForHTTPConnection$1$2.invoke(Kweb.kt:387)
	at kweb.Kweb$listenForHTTPConnection$1$2.invoke(Kweb.kt:54)
```

In WebBrowser.url we are in fact dropping the scheme:
```kotlin
    val url: KVar<String>
            by lazy {
                val originRelativeURL = URL.parse(httpRequestInfo.requestedUrl).pathQueryFragment
                val url = KVar(originRelativeURL)
                ...
                url
            }
```

The options I see are:
- try to get a "hacked" parser such as `URL.parse("http://kweb.io" + from)` going (because we don't have the info at the source, i.e WebBrowser.url). Can easily work, but if the user tries to access e.g the host, they're in for a surprise. Pretty nasty hack
- try to get a parser such as `URL.parse(httpRequestInfo.requestedUrl)`... which is basically what WebBrowser.url does and then it throws the result away. Smells pretty bad for concurrency as well. Eh.
- Have a `val WebBrowser.fullUrl : KVar<String>` and make the current WebBrowser.url a dependent KVar on it (I think you had a design for that somewhere). Looks pretty good tbh, plus not sure why we're missing that full url anyway?
- Whatever else you can come up with?

**Comment by sanity** [comment]
Hmm, definitely looks like a problem - could you clarify how you're trying to use it?  Is it possible to use `val url` directly without using the Galimatias parser?  If I recall correctly, your issue before was that it was stripping the query and fragment from the `path`, but you can now do something like:

```kotlin
url.value = "/path?query#fragment"
```

**Comment by alkoclick** [comment]
```kotlin
fun WebBrowser.getQueryParams(): Parameters =
    parseQueryString(
        URL.parse(httpRequestInfo.requestedUrl).query()?.replace("+", " ") 
        ?: ""
     )
```

(parseQueryString is from ktor)

Instead of that, I would love to instead do: 
```kotlin
fun WebBrowser.getQueryParams(): Parameters =
    parseQueryString(
        url(simpleUrlParser).query.value 
        ?: ""
     )
```

Generally there is a bunch of extension methods such as `val KVar<URL>.query` that I would like to use, but they are currently unusable :/

**Comment by sanity** [comment]
This should be an easy fix, just trying to think through the ergonomics.  How about something like this:

```kotlin
class WebBrowser {
   ...
    val gurl : KVar<URL> = url.map(object : ReversibleFunction<String, URL>(label = "gurl") {
        override fun invoke(from: String): URL {
            return URL.parse(this@WebBrowser.httpRequestInfo.requestedUrl).resolve(from)
        }

        override fun reverse(original: String, change: URL): String {
            return change.pathQueryFragment
        }
    } )
   ...
}
```

This would allow you to use the `KVar<URL>` extension methods on `gurl`:

```kotlin
gurl.query.value = "query"
```

**Comment by alkoclick** [comment]
Yeah, but I was trying to have the functionality of `WebBrowser.url` as well. This is currently `pushState` and I dunno if you're doing anything else with it? So this is about operating on WebBrowser.url using the methods created for Kvar (query, path, fragment, etc)

**Comment by sanity** [comment]
I'm afraid I'm not sure what you mean, could you give an example of how it should work?

**Comment by alkoclick** [comment]
No, sorry, my bad. I had missed that in your example, gurl is mapped on url (`url.map`). That is an easy fix indeed and has the functionality I expected, though I would also add some short documentation about this (previously some examples did `url(simpleUrlParser)` so maybe others like me are using this, and it's currently broken OOTB)

**Comment by sanity** [comment]
Gotcha, I'll search the documentation for references to `simpleUrlParser` and update them.
