### ISSUE TITLE
Add ability to register KVal/KVar listener with specified ID

### ISSUE THREAD

**Issue by marad** [kwebio/kweb-core#123]
I need the ability to clear my listener from KVar/KVal, but it would be very complicated keep track of every listener ID. 

I would like to give the listener specific ID so I can later use it to remove the handler:

```kotlin
const val MY_SPECIFIC_HANDLER_ID = 1234

someKVar.addListener(MY_SPECIFIC_HANDLER_ID) { old, new -> ... }

// somewhere later
someKVar.removeListener(MY_SPECIFIC_HANDLER_ID)
```

I can implement this change, but please tell me what you think of this idea.

**Comment by sanity** [comment]
It seems fine to optionally allow people to provide a `listenerId` when they do an `addListener`, but would you mind elaborating on why you need this?

**Comment by marad** [comment]
This was one of my experiments with KWeb. I don't think it was particularly good direction but "naming" listeners still seem to be useful.

In this attempt I had this model (it's very simplified here to illustrate my needs):

```kotlin
data class Note(val name: String, val blocks: List<Block>)
data class Block(val text: String)
```

I want to render note title and each block. Plot twist here is... the title and each block have the _contentEditable_ attribute set to _true_. 

So I have series of editable blocks which also update the model. I also want to have the ability to insert/remove new blocks.

I was thinking I should use `KVar<List<KVar<Block>>>` but just the type looks like it was a bad idea :) I'm still not really sure how to approach this. In Shoebox sources I've seen `renderEach()` method which seem to be what I need, but it's Shoebox specific.

**Comment by sanity** [comment]
Yes, this is actually something I've been thinking about, an extension function for KVar collections that doesn't rely on Shoebox - something like:

```kotlin
// Note: This is a proposed new API, it won't currently work
val c : KVar<List<Int>> = KVar(listOf(1, 2, 3))
// inside Kweb {}
renderEach(c) { v : KVar<Int> ->
  h1().text(v.map { it.toString() })
}
```

For now to render a collection you could do something like:

```kotlin
 val c : KVar<List<Int>> = KVar(listOf(1, 2, 3))

render(c.map { it.size }) { size ->
  for (ix in 0 until size) {
    h1().text(c[ix].map { it.toString() })
  }
}
```

To make the KVar user editable you could bind it to an input element's value, see [here](http://docs.kweb.io/en/latest/state.html#binding-a-kvar-to-an-input-element-s-value).

**Comment by marad** [comment]
Having this `renderEach` function would be great! (of course given that it would render only the changed items)

I ended up using `ObservableList<KVar<Block>>` and responding to adding and removing items by adding/removing DOM elements myself. This works pretty well (with fixes from pr #127), doing minimal changes to the DOM required. Also adding/removing blocks is reflected in the database, and changing any inner `KVar<Block>` also updates only this block in the  database. Works quite well.

As for input binding - at first I considered exactly that (with textareas) but I also want this text block to expand vertically as needed (no scrollbars). This is not very easy with textareas so I just use regular div with contenteditable:

```kotlin
internal fun ElementCreator<Element>.editor(text: KVar<String>) {
    val editor = div(mapOf("contentEditable" to true))
    editor.addClasses("editor", "mousetrap")
        .text(text.value)
        .spellcheck(false)
        .on.blur {
            editor.read.text.thenAccept {
                text.value = it
            }
        }
}
```

**Comment by sanity** [comment]
Created an issue for `renderEach`: #128

**Comment by sanity** [comment]
Regarding your `editor()` function, you might want to take a look at the use of `retrieveJs` here: https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/prelude.kt#L253

It is intended to cut out a browser-server round-trip by providing a JavaScript expression to evaluate when the event fires and return the value to the server with the event.

**Comment by marad** [comment]
Thanks for the tip! Is there a function to send an event/message to the server? Because I still need this value on the server for persistence. 

As I understand this, now I have two roundtrips - one is for `blur` event, and the second to get the text from element. This could be reduced to just one event-like message "editor updated" containing text.

**Comment by marad** [comment]
Oh, I see! Thanks!

```kotlin
internal fun ElementCreator<Element>.editor(id: String, text: KVar<String>) {
    val editor = div(mapOf("contentEditable" to true, "id" to id))
    editor.addClasses("editor", "mousetrap")
        .text(text.value)
        .spellcheck(false)
        .on(retrieveJs = "document.getElementById('${editor.id}').innerText").blur {
            if (it.retrieved != null) {
                text.value = it.retrieved!!
            } else {
                editor.read.text.thenAccept {
                    text.value = it
                }
            }
        }
}
```

**Comment by marad** [comment]
But still - is there a way to asynchronously send custom message from client to server? This would allow handling custom cases that KWeb API doesn't yet support (or even couldn't).

**Comment by sanity** [comment]
> retrieved can only be null if the retrieveJs doesn't return anything or is empty?

I believe this should be the case, yes - you can find the relevant code [here](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/Element.kt#L316).

**Comment by sanity** [comment]
Going to close this for now as I'm not aware of a use-case for specifying the listener id (rather than it being generated as it is now).
