### ISSUE TITLE
Removing child nodes at index doesn't work properly

### ISSUE THREAD

**Issue by marad** [kwebio/kweb-core#125]
I've found that removing child nodes when there is more complicated structure below works inconsistent.

After a little investigation it looks like the code uses `element.childNodes` and not `element.children`.

For me de difference is quite big: 
![image](https://user-images.githubusercontent.com/1618489/80857360-dad73d00-8c51-11ea-8ccc-589d816dd010.png)

Between elements there are empty `#text` nodes. I havent checked that, but I'm pretty sure that this also causes the #124 

Easy fix would be to just use `children` instead of `childNodes`. It would work more intuitively, but we'll loose the ability to manage text nodes inside tags (they would have to be wrapped in some kind of tag like a `<span>`. 

I have a observable collection of elements and want to insert/remove page elements based on changes to that collection. Right now I cannot use the same index for position and collection because of this issue.

What do you think about it? If this is ok I can prepare a PR.

**Comment by sanity** [comment]
Yes, I think the change you suggest is a good one, please feel free to prep a PR.

**Comment by marad** [comment]
Sure. Will do :)

**Comment by marad** [comment]
I tested the newest release and now it works great. Closing this one.
