### ISSUE TITLE
https demo does not work: "SSL_ERROR_RX_RECORD_TOO_LONG"

### ISSUE THREAD

**Issue by dertroglodyt** [kwebio/kweb-core#131]
Tested on localhost

Log:
[main] INFO kweb.WebBrowser - Initializing Kweb listening on port 16097
[main] WARN kweb.WebBrowser - Debug mode enabled, if in production use KWeb(debug = false)
[main] INFO org.eclipse.jetty.util.log - Logging initialized @1013ms to org.eclipse.jetty.util.log.Slf4jLog
[main] INFO Application - No ktor.deployment.watch patterns specified, automatic reload is not active
[main] INFO Application - Responding at http://0.0.0.0:16097
[main] INFO Application - Responding at https://0.0.0.0:9091
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.24.v20191120; built: 2019-11-20T21:37:49.771Z; git: 363d5f2df3a8a28de40604320230664b9c793c16; jvm 12.0.2+10
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@6e20b53a{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:16097}
[main] INFO org.eclipse.jetty.util.ssl.SslContextFactory - x509=X509@4bc222e(test,h=[localhost],w=[]) for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_256_GCM_SHA384 enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_128_GCM_SHA256 enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA256 enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDH_RSA_WITH_AES_256_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_DHE_RSA_WITH_AES_256_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_DHE_DSS_WITH_AES_256_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA256 enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDH_RSA_WITH_AES_128_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_DHE_RSA_WITH_AES_128_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_DHE_DSS_WITH_AES_128_CBC_SHA enabled for Server@2dc9b0f5[provider=null,keyStore=null,trustStore=null]
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@1b7cc17c{SSL,[ssl, alpn, h2, http/1.1]}{0.0.0.0:9091}
[main] INFO org.eclipse.jetty.server.Server - Started @1560ms
[main] INFO kweb.WebBrowser - KWeb is listening on port 16097

**Comment by alkoclick** [comment]
Are you connecting to port 9091? I am running the demo and I cannot replicate, it works as expected.

Do note that the port defined in `Kweb(port = X...)` is for the http connection, while the one defined in the `SSLConfig(port = ...)` is the one for https

**Comment by dertroglodyt** [comment]
Ouch, that should have been obvious. Didn't spot the default parm in SSLConfig().
Sorry for bothering you.
