### ISSUE TITLE
Remove examples from Kweb code

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#135]
Basically, since #114 is done, we need to remove the examples that are still in Kweb code (Unless we're using git sub repos and I didn't notice?) 

There's also various samples peppered in code that should be removed, or at least organized in a more coherent way

**Comment by ethanmdavidson** [comment]
Yes, everything in [the demos folder](https://github.com/kwebio/kweb-core/tree/master/src/main/kotlin/kweb/demos) has been moved to the [kweb-demos repo](https://github.com/kwebio/kweb-demos). Simply an oversight on my part that they weren't removed from this repo. Also see #116

**Comment by sanity** [comment]
Yes, I think #116 is the main blocker to doing this.

**Comment by sanity** [comment]
@alkoclick On the topic of the examples peppered around the code, they definitely need to get cleaned up, although note that some of them might be referenced from kdoc comments - and I think it makes sense to keep the sample code close to the kdoc that references it.

**Comment by alkoclick** [comment]
I'm okay with having samples in some centralized repo. You could also reference samples that are part of our docs repo and I think it'd be even better to expose them like that. People will be able to actually find them and understand basic guidelines of how to build stuff. I disagree that it should stay close to the kdoc that references it - that's what `@see` and other link constructs are for. 

As a starter dev, it's not easy or obvious where to find these examples
As a seasoned dev who is trying to debug an issue, they are actively getting in my way

**Comment by sanity** [comment]
Can Kdoc's `@sample` directive reference a function in a remote repository?  I'm not sure it can.

**Comment by alkoclick** [comment]
One issue that we will need to address sooner or later (though I'm not sure if this is the time and place) is the fact that our sample repo is not (at least in my understanding) synced to the latest Kweb changes. If we break it in a new release, we will never know. If we address that problem, then our solution will also be capable of dealing with this issue (because clearly we have found a way to cleanly connect the two).

Git submodules may be a way out here, providing the best of both worlds

**Comment by sanity** [comment]
Yeah, I'm open to ideas on it - not familiar with Git submodules but happy to look into it.

**Comment by sanity** [comment]
Seems like we need a push on either the `kweb-core` or `kweb-demos` repositories, and perhaps the `kweb-template` one too, to trigger rebuilds of each of these repositories using the latest code.

Not sure how easy it is for events in one repository to trigger an action in another, [this](https://help.github.com/en/actions/reference/events-that-trigger-workflows) seems to be relevant though.

**Comment by sanity** [comment]
I think synchronizing kweb-core with the demos probably isn't worth it, the [Freenet website](https://github.com/freenet/freenetorg-website/) is the best demo we've got right tnow.
