### ISSUE TITLE
Extract Kweb param parsing functionality into a separate function

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#136]
This is currently buried in the path receiver / render functionality. Extracting it will allow us to test it more efficiently, while also reusing it for Ktor routing, [which currently does not parse params](https://github.com/kwebio/kweb-core/blob/75f617756ca12e953b3738c6fcdea992acf76f58/src/main/kotlin/kweb/KtorFeature.kt#L42) in the "Kweb way" because of this

**Comment by sanity** [comment]
Pretty sure this is fixed, reopen if not.
