### ISSUE TITLE
Consider whether Kotlin's new StateFlow should impact KVars

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#137]
The new [StateFlow](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/index.html) API seems to have a number of things in common with Kweb's [KVar](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/state/KVar.kt).

**Comment by alkoclick** [comment]
Looks like a pretty interesting concept and I definitely like the idea. I would like to see KVars gone, not because I dislike them, but because I feel there are a few implementations of this concept already and we should be sticking with one of them

**Comment by sanity** [comment]
Yeah, I always knew I was reinventing the wheel with KVars and KVals, but at the time I couldn't find anything that fit what Kweb needed.

The only cautionary note is that, because KVars and KVals are used all over the place in Kweb I don't want to sacrifice API ergonomics in order to reuse something that exists.

But if this (or something else) can effectively replace KVars and KVals without making compromises elsewhere then it's a nobrainer.

**Comment by sanity** [comment]
Looked into it, StateFlow is quite similar but I don't think it quite fits our use-case, also it's not stable yet.
