### ISSUE TITLE
Using Parent-Chaining to improve DOM manipulation

### ISSUE THREAD

**Issue by djeang** [kwebio/kweb-core#140]
Hi,
I am newbie in Kotlin but i fell that using [parent-chaining pattern](https://github.com/djeang/parent-chaining/blob/master/readme.md), Dom library could be improved a bit. What do you think of ?

**Comment by sanity** [comment]
It's not that different to how Kweb's DSL currently works, except Kweb uses code blocks for nesting - which I think makes sense.

Were there any particular advantages relative to the current approach?
