### ISSUE TITLE
Make `checked` work properly in InputElement

### ISSUE THREAD

**Issue by marad** [kwebio/kweb-core#146]
Input is checked when the tag contains valueless attribute `checked`. The value of this attribute is ignored.

So all of this would result in checked checkbox:
```HTML
<input type="checkbox" checked/>
<input type="checkbox" checked="true"/>
<input type="checkbox" checked="false"/> <!-- this one is also checked -->
```

Meanwhile, KWeb is just setting the `checked` attribute which results in checkbox always checked:

https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/prelude.kt#L146

Based on `checked` parameter this method should add or remove the attribute.

**Comment by sanity** [comment]
Ah, I wasn't aware of this - thanks for the fix!

**Comment by sanity** [comment]
Released in `0.7.16`

**Comment by marad** [comment]
Sure, it was surprising to me also when I first learnt it :)

**Comment by sanity** [comment]
<insert grumbling about javascript here> ;)
