### ISSUE TITLE
`render()` function is losing context of specific element it's in

### ISSUE THREAD

**Issue by marad** [kwebio/kweb-core#148]
This won't compile:

```kotlin
fun ElementCreator<TbodyElement>.foo(kvar: KVar<SomeDto>) {
  render(kvar) { data -> 
    tr() // <- this is bad
  }
}
```

This is because the definition of `render()` specifies the block of type `ElementCreator<Element>.(T) -> Unit`, here: https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/state/render.kt#L18

So inside the `render()` function we have the context of `Element` instead of original `TbodyElement` but the `tr()` method is available only in context of the latter.

**Comment by sanity** [comment]
Oh, yes - originally I thought it would be nice to try to use the type system to enforce HTML semantics, but I suspected the cost might outweigh any benefit and this lends evidence to it.

**Comment by sanity** [comment]
Ah, yes - the reason this happened was the need to use noop `<span>` elements within `render()`, so the `block` receiver had to be a general `ElementCreator<Element>`.

I'd like to get rid of the noop `<span>` at some point, but in the meantime the quick solution is probably for all these element creation extension functions to extend `ElementCreator<Element>`.

**Comment by marad** [comment]
While I think that we could make use of the type system in that way I also agree that for now this solution is ok.
