### ISSUE TITLE
`render()` should not use a <span> to contain rendered elements

### ISSUE THREAD

**Issue by marad** [kwebio/kweb-core#151]
The `render()` function internally uses `span` as it's container element. Removing it would be a god send, but I don't think there is an easy way to do this so what we can do instead is provide a way for user to give it some custom element as container.

The problem I've stumbled upon goes like this. I want to create dynamically filled dropdown using fomantic. So I did this:
```kotlin
val areaId = KVar("")
div(fomantic.ui.search.selection.dropdown).new {
  input(type = InputType.hidden).setValue(areaId, updateOn = "change")
  i(fomantic.dropdown.icon)
  div(fomantic.menu).new {
    render(state.listAreas()) { areas ->
      areas.forEach { area -> div(fomatnic.item).setAttributeRaw("data-value", area.id).text(area.name)
    }
  }
}
```

This works, but because of the span it doesn't look right (styling is wrong). So instead I think we could do this:

```kotlin
val areaId = KVar("")
div(fomantic.ui.search.selection.dropdown).new {
  input(type = InputType.hidden).setValue(areaId, updateOn = "change")
  i(fomantic.dropdown.icon)
  render(stat.listAreas(), container = div(fomantic.menu)) { areas ->
    areas.forEach { area -> div(fomatnic.item).setAttributeRaw("data-value", area.id).text(area.name)
  }
}
```

Tell me what do you think.

**Comment by marad** [comment]
I just thought that if we went this way it would be pretty easy to make an extension function that would make things even cleaner (IMO anyway 😄)

```kotlin
div(fomantic.menu).render(state.listAreas()) {
  // ... 
}
```

I'm not sure about the name I think it would be confusing to call it `render` here.

**Comment by marad** [comment]
I've experimented with this a bit and it seem to work fine but I'm not sure what to do with this:

https://github.com/kwebio/kweb-core/blob/c2073e9e5aeebe232772b802edf1a38a7509caa6/src/main/kotlin/kweb/Element.kt#L426-L433

I think that the first `onCleanup` is not necessary because render is not managing the container anymore (it should probably just stay in the old `render` function), but the second one looks important and I have no idea how to achieve that inside the `Element`.

**Comment by sanity** [comment]
Requiring a wrapper element like the span was kinda a kludge from the start, to make it easy to replace the rendered content when the KVar updates.

But ElementCreators remember the elements they create so it should be possible to skip the span wrapper provided the ElementCreator ensures that the right DOM elements are replaced and the replacements go in the appropriate positions under their parent element.

In exchange for doing this server-side housekeeping we shouldn't need any wrapper element at all - would that address your use case?

**Comment by marad** [comment]
Yes, getting rid of wrapping `<span>` would do fix things for me. So as I understand - the render function on re-render should remove all `elementsCreated` and then start a rendering new ones? Does removed elements also get removed from `elementsCreated`?

**Comment by sanity** [comment]
I think if we reuse the same `ElementCreator` then it should be reset to the state it would have been in with no elements, so yes I think we should remove elements from `elementsCreated`.  

We'd also need to make sure that new elements get inserted at the same positions under the parent element as the replaced elements.

Another approach would be to use a new `ElementCreator` every time the `KVar` is re-rendered, but it's not clear to me at this point which would be cleaner.

**Comment by marad** [comment]
Are there any other important factors? Like speed for example?

**Comment by sanity** [comment]
It should be possible to make this improvement without sacrificing speed.  Currently we can just call [Element.removeChildren()](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/Element.kt#L208) on the wrapper `<span>`, which lets the browser do the work.

The proposed new approach would require the server to pass a list of the element IDs to be deleted to the browser which would then delete them.  I don't anticipate this being inefficient unless there are a **very** large number elements to be deleted.

**Comment by marad** [comment]
> Oh, and we also need to ensure that any subsequently added elements are added in the same position as those they replace.

This one can be hard. If we don't have the container element the children added by render could be interleaved with other components. Then re-render would have a really hard time to address that.

**Comment by sanity** [comment]
Yeah, getting element replacement right in situations where there are sibling elements that are not part of the `render {}` block is the headache that prompted the `<span>` solution in the first place.

I'm confident it's doable though if we think about the problem the right way, needs more thought though.

**Comment by sanity** [comment]
Note: version 0.7.19 doesn't eliminate the need for a container element, but it does allow you to change the type of element used with `render(containerElementTag = "li") { .. }`.

**Comment by marad** [comment]
This is nice! 
Would it work with classes like `render(containerElementTag = "li.item")`?

**Comment by sanity** [comment]
Not right now I'm afraid, although I could add another parameter to `render` to support configuration of that element - although this would just be a stop-gap until we can remove the requirement for the container element altogether.

The stop-gap would be something like:

```kotlin
render(containerElementTag = "li", containerConfig = { it.classes("item") }) { ... }
```

Not very elegant, but hopefully temporary - would this work for you?

**Comment by marad** [comment]
Well it would work for this exact use-case. Why you don't like the idea of just passing `Element` as the parameter? User could preconfigure it however they like.

**Comment by sanity** [comment]
Good point, just released `0.7.20` which supports this:

```kotlin
        render(container = { li().classes("item") }, value = v) { ... }
```

**Comment by marad** [comment]
So would something like this work?

```kotlin
val el = li().classes("item")
render(container = { el }, value = v) { ... }
```

**Comment by sanity** [comment]
Yes - that would probably work with the current implementation - so I guess it was inaccurate to say it would *ensure* use of the parent ElementCreator, but it would encourage it.

Is there a particular reason to pass in an `Element` rather than creating it within the `container` function?

**Comment by sanity** [comment]
Somewhat related: #128, #177

**Comment by sanity** [comment]
After quite a bit of thought and discussion with @Derek52, I think I have a solution.

Rather than wrapping the `render`ed elements in a noop marker `<span>`, we add a noop "begin" <span> before the rendered elements, and an "end" <span> after them.  Note these spans will be *siblings* of the newly added elements.  The ids of these marker spans are noted within the `render` function.

We modify `ElementCreator` so that instead of providing a `position`, we can provide the id of an element before which any new elements will be added using [insertBefore()](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore). We can use this to insert elements before the end <span> - which will ensure they're added in the correct order.

We should also predefine a JavaScript function that can be given two element ids and which will delete any sibling elements between them. This can be used by `render` to clear previously added elements before re-rendering. It will be important to ensure that `ElementCreator.cleanup()` is called for the deleted elements.

**Comment by sanity** [comment]
Render was redesigned a while ago to remove the `<span>`.
