### ISSUE TITLE
setAttributeRaw, js and css

### ISSUE THREAD

**Issue by prohfessor** [kwebio/kweb-core#152]
Hello! Recently I began to study Kotlin and KWeb and ran into a couple of problems:
1. setAttributeRaw(). in file Element.kt it is written:
     * Set an attribute of this element.  For example `a().setAttribute("href", "http://kweb.io")`
     * will create an `<a>` element and set it to `<a href="http://kweb.io/">`.

But when I try to change, for example 'id'
a().setAttributeRaw("id", "newid")
I get:
id=&quot newid&quot
How can I change correctly 'id'? I do that way:
a(attributes = mapOf("id" to "newid"))

2. Can i change the variable 'ttt' in javascript from KWeb?:
element("ttt2").innerHTML(
"""
<script>
var ttt="";
</script>
"""

3. How to insert in header link to css and js file?
Now I insert something like this:

            doc.head.new {
		element("ttt").innerHTML(
			"""
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
<script>
var ttt="";
</script>
			"""
		)
            }

**Comment by prohfessor** [comment]
i found how to embed javascript - execute()

**Comment by marad** [comment]
Hi @prohfessor. Your question is a bit chaotic so I'll try my best to answer each point as I understand your problem (and I'm not sure if I do all the way).

**1.** Here I'm not sure what is the problem. In my pet project I'm using `setAttributeRaw` this way:

```kotlin
div(fomantic.item).setAttributeRaw("data-value", area.id).text(area.name)
```
and it works all right. Produces following HTML:

```HTML
<div id="Ke" class="item selected" data-value="261f5fb6-e4c9-4945-a92a-2998ffdc8004">
       Sample Item
</div>
```


**2.** While you can change the value if it's **global** with simple `execute("ttt = 'new value'")` you shouldn't have global variables in the first place 🙂 What is the reason you want to do this? Maybe there is another way to achieve the same effect?


**3.**
```kotlin
doc.head.new {
    element("script", mapOf(
            "src" to  "https://unpkg.com/leaflet@1.6.0/dist/leaflet.js",
            "integrity" to "sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==",
            "crossorigin" to ""
    ))
}

```

**Comment by prohfessor** [comment]
1. setAttributeRaw changes the quotation marks to a &quot in front and the end of the text

**Comment by DineshSolanki** [comment]
> 
> 
>     1. setAttributeRaw changes the quotation marks to a &quot in front and the end of the text
works correctly on my side. 
<a id="newid" href="#"></a>
maybe the issue in something else, your id might contain some unsupported character maybe.

**Comment by DineshSolanki** [comment]
closing as can't reproduce and inactivity.
