### ISSUE TITLE
Using the same fomantic plugin instance in multiple Kweb instances fails to decorate HTML pages

### ISSUE THREAD

**Issue by mkit** [kwebio/kweb-core#155]
I used 0.7.17 version of core and the fomantic styles are not applied in my application. I am using JDK8 (cannot upgrade).
Is there any change between 0.7.11 and 0.7.12 that would alter the way fomantic styles are applied?
I want to use the latest version but lacking fomantic styles prevents me from doing that.

**Comment by sanity** [comment]
Hmm, that's not good.  Do you see the styling applied in this Demo app? http://demo.kweb.io:7659/lists/7c5b34  It's using a recent version of Kweb.

**Comment by mkit** [comment]
Thanks for coming back. The demo works fine. Not sure what is happening but the ``FomanticUIPlugin`` executes the ``decorate`` method but the final (i.e. rendered website) does not have header as "enriched" by the ``decorate`` method. It seems like the header was created ignoring the ``FomanticUIPlugin``. I have the plugin in the list of plugins.

**Comment by mkit** [comment]
OK, I found the reason. I started multiple instances of the Kweb server in a single JVM. This causes the plugin (which is a singleton) to go crazy. Do you think it would be possible to address this in a future release? Thanks in advance for your reply.

**Comment by sanity** [comment]
Oh, interesting.  although I'm not sure I understand why using a singleton was a problem, was it something to do with dependency resolution, or perhaps the `StaticFilesPlugin`?

**Comment by sanity** [comment]
Oh, hmm, I can definitely remove the singletons - although I'm not sure why using a singleton would cause a problem, that may be a bug in its own right.  I'm guessing maybe the `StaticFilesPlugin`, or some weirdness in plugin dependency resolution.

**Comment by sanity** [comment]
One quick non-breaking way to get rid of the singletons would be something like `val fomantic get() = FomanticUIPlugin()`.

**Comment by mkit** [comment]
Not sure what is causing it if you try to run two instances of the Kweb. :-(

**Comment by mkit** [comment]
Thanks a lot for your help.

**Comment by sanity** [comment]
No problem, I'm going to leave this open to investigate why the singleton plugins were causing problems.
