### ISSUE TITLE
Call fomantic transitions from kotlin

### ISSUE THREAD

**Issue by mkit** [kwebio/kweb-core#156]
I am new to the fomantic framework but I am getting to like it - especially with Kotlin. I think I managed to grasp the idea of static styling but I wanted to ask if you could advise me how can I call transitions so I could implement rotating dividers for example. Thanks in advance for your reply.

**Comment by sanity** [comment]
Hi, something like this should work:

```kotlin
  button.on.click {
    execute("$('.autumn.leaf').transition('shake');")
  }
```

**Comment by mkit** [comment]
Thanks a lot @sanity
