### ISSUE TITLE
Fomantic with kotlin and adding your own custom attributes

### ISSUE THREAD

**Issue by mkit** [kwebio/kweb-core#157]
Again a stupid question from my side but could you advise me how to create a tab binding with fomantic in kotlin?

I have something like this:
```
                  div(fomantic.ui.three.wide.column).new {
                       div(fomantic.ui.vertical.fluid.tabular.menu).new {
                            a(fomantic.ui.item).text = KVar("Test1")
                            a(fomantic.ui.item).text = KVar("Test2")
                            a(fomantic.ui.item).text = KVar("Test3")
                        }
                    }
                    div(fomantic.ui.thirteen.wide.column).new {
                        ...
                    }
```

How do I connect tabs with the divs. I tried to follow the Fomanitc documentation and managed to reach some weired solution . Just wanted to confirm if I am doing things right? Shall I just extend the attributes with one entry for ``data-tab``?

**Comment by mkit** [comment]
I think I sort it out. Thanks in case you start looking into it.

**Comment by sanity** [comment]
Sorry I didn't reply sooner, I did look at this but it wasn't clear whether it was a Kweb issue or a Fomantic issue.
