### ISSUE TITLE
Update Fomantic-UI from 2.8.4 to 2.8.6

### ISSUE THREAD

**Issue by mkit** [kwebio/kweb-core#158]
Which version of fomantic is used in this project? Is there a way to add a support for the the equal height grid?

**Comment by sanity** [comment]
Currently [2.8.4](https://github.com/kwebio/kweb-core/tree/master/src/main/resources/kweb/plugins/fomanticUI/static).

**Comment by mkit** [comment]
Thanks @sanity

**Comment by frnknglrt** [comment]
Hello mkit,

it is quite easy to extend the css classes provided by fomantic using a kotlin extension function. Please note the following example:

```kotlin
val FomanticUIClasses.required : FomanticUIClasses
    get() {
        classes("required")
        return this
    }
```

I ended up with many extension functions in my project using kweb. If it helps i can provide the extension functions/variables i already added.
