### ISSUE TITLE
jquery callback to kotlin

### ISSUE THREAD

**Issue by mkit** [kwebio/kweb-core#159]
I am using a 3rd party jquery component on my website - a map. I would like to be able to handle an onMapElement click callback in Kotlin. Basically, the map I am embedding has onCountryClick function, however it this callback in in jQuery. Is there a way for me to handle onCountryClick in Kotlin? Some sort of relay?

**Comment by frnknglrt** [comment]
Hello mkit,

you can register callbacks like this: 

```kotlin

private fun ElementCreator<*>.listCameras(onCameraListResponse:(GetCamerasResponse)->Unit){
    val callbackId = Math.abs(random.nextInt())
    val js = """
        Html5Qrcode.getCameras().then(devices => {
          /**
           * devices would be an array of objects of type:
           * { id: "id", label: "label" }
           */
          callbackWs($callbackId ,{cameras: devices});
        }).catch(err => {
          callbackWs($callbackId, {error: err});
        });
    """.trimIndent()
    this.browser.executeWithCallback(js, callbackId){
        val resp : GetCamerasResponse = gson.fromJson(it.toString())
        onCameraListResponse(resp)
    }
}

class GetCamerasResponse(
        val cameras: List<CameraDevice>? = null,
        val error: String? = null
)

class CameraDevice(
        val id: String,
        val label: String
)
```

It's a helper function i wrote to integrate the HTML5-QR-Code library. But i think you can easily adapt this to your use case. It works as follows:

1. You have to add the javascript code which wires the callback in your java script code to the kweb callbackWs function. You can send arbitrary json data back to the kweb backend using the second parameter of callbackWs. The first parameter is used by kweb to route the response message to your kotlin message handler. 

2. Inside of your kotlin message handler you have do deserialize the json data you received according to the format you've sent in step 1. I made a small data class for that purpose.

3. I hope that helps that you can help yourself.

**Comment by mkit** [comment]
Thank you very much @frnknglrt
