### ISSUE TITLE
Is it possible to run Kweb with Kotlin 1.2

### ISSUE THREAD

**Issue by mkit** [kwebio/kweb-core#160]
I wanted to use Kweb with as a part of a bigger tool but the tool is written in Kotlin 1.2 so there is no chance to bump the version 1.3 any time soon. Do you think it would be possible without huge loss of features? What would be the best approach?
Thanks in advance for your reply.

**Comment by sanity** [comment]
Hi, I can't think of anything critical that Kweb relies on that was added to Kotlin after 1.2, so my suggestion would be to try it.  It might be possible to override the Kotlin version in your `build.gradle`, the alternative would be to create a 1.2 fork of Kweb.

**Comment by mkit** [comment]
Thanks, but it has dependency on ktor which is in 1.3 not sure if this can be overcome

**Comment by sanity** [comment]
Ah, yes - if Ktor requires 1.3 then that's going to be a problem I'm afraid :(
