### ISSUE TITLE
How to implement file upload?

### ISSUE THREAD

**Issue by Kinchkun** [kwebio/kweb-core#161]
Hi,

I would like to use Kweb to implement a simple form, for collecting some data and optional an attachment file.
I don't use the HTML "submit" form feature; instead on submit I read the entered values with KVar bindings and send the data to an external backend (written in Dropwizard).

Can you give me a hint how to implement the file upload itself using Kweb? Can I access the file as inputstream somehow?

Thank you.

**Comment by sanity** [comment]
Hi, sorry for the slow reply.  I haven't tried this but it should be possible to create a file upload [plugin](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/plugins/KwebPlugin.kt), by overriding the `appServerConfiguratior()` function, which will give you access to Ktor's [Routing](https://api.ktor.io/0.9.5/io.ktor.routing/-routing/index.html) object.

From there it should just be a question of following Ktor's [documentation](https://ktor.io/servers/uploads.html) for file uploads.

If you are able to create a generic file upload plugin I'd be happy to add it to Kweb.

**Comment by Kinchkun** [comment]
Hi, thank you for your tips. I will look what I can do and give you feedback if I was able to write a generic plugin :)

**Comment by DineshSolanki** [comment]
@Kinchkun have you found a way? I'm looking for the same.
