### ISSUE TITLE
Get Kweb working on Kotlin Native

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#162]
[Apparently](https://medium.com/@kpgalligan/ktor-and-kotlin-native-fb5c06cb920a) Ktor 1.4 works on Kotlin Native, which means that Kweb should also work with it - although it will probably require some modifications.

**Comment by frnknglrt** [comment]
Hello,

how important is the Kotlin Native support for KWeb? I know that there are many people outside who dislike the ressource consumption of JVM but i see this as a non-issue for me personally. Especially given the fact that there are hosters like Contabo or Hetzner who offer VMs with large amounts of ram for very little money and server locations in US + EU. 

Further, the actual ressource consumption of KWeb is pretty low. I run multiple processes of KWeb on a single Raspberry Pi and the database (MongoDB) is also on that machine. This aforementioned raspberry pi even runs a Jenkins (*)  and an instance of Gitea. I had never any ressource problems or reduced latency.  

Support for Kotlin Native would most likely require replacing Gson with kotlinx.serialization and maybe some changes to remove operations that rely on reflection. Most likely this would increase the build time and thus slow down the compile + debug + run cycle of KWeb which is currently pretty short. Also one would require a database binding and other third party libararies that also supports Kotlin native. 

Here is a summarized pro/con list of Kotlin Native for KWeb:
 + PRO: Reduced memory consumption
 + PRO: Reduced overall binary size which is important when packaging apps as container (e.g. docker)
 - CON: Most likely increased compile time
 - CON: Most likely some effort
 - CON: Port to Kotlin Native may require backward incompatible changes

**Comment by frnknglrt** [comment]
Related to issue #59 and #145

**Comment by sanity** [comment]
Thank you for the comment.

I'd say this is a low priority, something that would be nice to do if it's easy but not if it comes with a cost, and you list some valid concerns.

I do want to migrate away from kotson/gson anyway because it is no-longer maintained, and kotlin serialization avoids reflection and is more efficient - but that's a separate issue.

**Comment by sanity** [comment]
I went ahead and closed this due to the lack of a concrete use case.
