### ISSUE TITLE
FileReader API Support ?

### ISSUE THREAD

**Issue by DineshSolanki** [kwebio/kweb-core#165]
I was wondering if the [FileReader Web API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) support is possible in such a way that we can, bind a function to the FileReader Load event and get a response in a KVar, to eliminate the need to listen to the event using javascript which then doesn't return anything, and limits us to do our work in there. which unbinds my img element from KVar binded to its 'src' attribute.
@sanity referred to the relevant code to make something to support it, but I couldn't get my head around it, any example or help ?

**Comment by DineshSolanki** [comment]
I'm looking to do something Like this -
```kotlin
var imageString = KVar("")
        doc.body.new {
            input(InputType.file).let { fileInput ->
                fileInput.on.change {
                    val file = fileInput.files[0]
                    val reader = FileReader()
                    reader.on.load {
                        imageString = reader.result
                    }
                    reader.readAsDataURL(file);
                }
            }
            img().setAttribute("src", imageString)
        }
```

**Comment by sanity** [comment]
This would be very useful, however it's unlikely to be something I can get to myself in the next couple of weeks due to other commitments.  If anyone would like to take this on I'd be happy to provide advice and support.

**Comment by DineshSolanki** [comment]
@sanity I would work on it, but I don't really know how to start, I looked into files that you referred to, and I get that events are defined there, can you give me a little example of something like this, where a javascript object is made to work like it?

**Comment by frnknglrt** [comment]
Does this help?

**The element**
```
class FileUpload(
        val fileName : String,
        val fileSize: String,
        val base64Content: String
)

class FileFormInput(
        override val actualValue: KVar<String>,
        override val isRequired:Boolean,
        override val label:String?,
        private var validator: ValidationFunc?=null,
        override val errorMessage: KVar<String?> = KVar(null),
        private var inputMissingErrorMessage: String? = null) {

    private lateinit var _inputElement: Element

    override val inputElement: Element
        get() = _inputElement


    fun setInputElement(e:Element){
        this._inputElement = e
    }

    fun retrieveFile(onFileRetrieveCallback:(FileUpload)->Unit){
        val callbackId = Math.abs(random.nextInt())

        val js = """
                let fd = document.getElementById("${inputElement.id}").files[0]
                let fr = new FileReader()
                fr.readAsDataURL(fd)
                fr.onload = function(){
                    callbackWs($callbackId,{base64Content: fr.result, fileSize: fd.size, fileName: fd.name});
                }
            """.trimIndent()

        inputElement.browser.executeWithCallback(js, callbackId) { result ->
            logger.info("Result is ${result.toString()}")
            onFileRetrieveCallback(gson.fromJson(result.toString()) as FileUpload)
        }
        inputElement.creator?.onCleanup(true) {
            inputElement.browser.removeCallback(callbackId)
        }
    }
}


fun ElementCreator<*>.fileInput(label: String?=null, placeholder:String?=null, required:Boolean=false, bindTo: KVar<String>) : FileFormInput{
    val formInput = FileFormInput(bindTo, required, label)

    val class_ = if(required){
        fomantic.ui.required.field
    } else {
        fomantic.ui.field
    }

    div(class_).new {

        formInput.errorMessage.addListener { old, newError ->
            if(newError!=null){
                this.parent.addClasses("error")
            }
            else{
                this.parent.removeClasses("error")
            }
        }

        label?.let {
            label().text(label)
        }
        div(fomantic.ui.input).new() {
            val input = input(InputType.file, placeholder = placeholder)
            formInput.setInputElement(input)
        }
    }

    return formInput
}
```

**Usage**
```
val fileField = fileInput(null, "", false, KVar(""))
fileField.onFileSelect {
    fileField.retrieveFile { fd ->
         logger.info("Received file ${fd.fileName}")
    }
}
```

**Comment by DineshSolanki** [comment]
@frnknglrt  you're Awesome, This works great. and I think we should cut on Label, and bindTo, bindTo is basically useless here, instead the work would be done in retriveFile.
Thank you for this

**Comment by DineshSolanki** [comment]
I introduced some changes in it. -
```kotlin
package kweb.file_upload

import com.github.salomonbrys.kotson.fromJson
import kweb.*
import kweb.plugins.fomanticUI.fomantic
import kweb.util.gson
import kweb.util.random
import kotlin.math.abs

class FileUpload(
        val fileName: String,
        val fileSize: String,
        val base64Content: String
)

class FileFormInput {

    private lateinit var _inputElement: Element

    val inputElement: Element
        get() = _inputElement


    fun setInputElement(e: Element) {
        this._inputElement = e
    }

    fun setAccept(acceptedTypes: String): Unit = inputElement.execute("${inputElement.jsExpression}.accept=\"$acceptedTypes\";")
    fun isMultiSelect(isMultiple: Boolean): Unit = inputElement.execute("${inputElement.jsExpression}.multiple=\"$isMultiple\";")
    fun onFileSelect(onFileSelectCallback: () -> Unit) {
        inputElement.on.change { evt ->
            logger.info(evt.retrieved)
            onFileSelectCallback()
        }
    }

    fun retrieveFile(onFileRetrieveCallback: (FileUpload) -> Unit) {
        val callbackId = abs(random.nextInt())

        val js = """
                let fd = document.getElementById("${inputElement.id}").files[0]
                let fr = new FileReader()
                fr.readAsDataURL(fd)
                fr.onload = function(){
                    callbackWs($callbackId,{base64Content: fr.result, fileSize: fd.size, fileName: fd.name});
                }
            """.trimIndent()

        inputElement.browser.executeWithCallback(js, callbackId) { result ->
            logger.info("Result is $result")
            onFileRetrieveCallback(gson.fromJson<FileUpload>(result.toString()))
        }
        inputElement.creator?.onCleanup(true) {
            inputElement.browser.removeCallback(callbackId)
        }
    }
}


fun ElementCreator<*>.fileInput(name: String? = null, initialValue: String? = null, size: Int? = null, placeholder: String? = null, attributes: Map<String, Any> = attr): FileFormInput {
    val inputElement = input(InputType.file, name, initialValue, size, placeholder, attributes)
    val formInput = FileFormInput()
    formInput.setInputElement(inputElement)
    return formInput
}
```

and here's how I used it -
```kotlin
var imageString = KVar("")
    doc.body.new
    {
        val input = fileInput()
        input.onFileSelect {
            input.retrieveFile {
                imageString.value = it.base64Content
            }
        }
        input.inputElement.setAttributeRaw("hidden", true)
        img().setAttribute("src", imageString)
    }
```

**Comment by DineshSolanki** [comment]
@frnknglrt can you also look into making Multiple file retrieval, as an Array of **class FileUpload**?

**Comment by frnknglrt** [comment]
I am glad that it did help you. Regarding the multi upload: 

I would not run multiple uploads in parallel. Maybe allow one upload at a time and render the list of uploaded files above. Maybe you can put the uploaded file to a KVar<List<FileData>> for the time being. If you upload a lot of files, the process may hog memory but this will not be a problem until you have a lot of uploads happening in parallel. 


However, you implicitly raised an interesting concern. It would be quite helpful to have a progress indication when uploading bigger files via slow link. I'll think about this and maybe come up with a draft. 

The label and the bindTo variables are remaining artifacts of validation infrastructure i had in place where i used the upload. However, that code i nothing i'm proud of...

**Comment by DineshSolanki** [comment]
I think the progress bar should not be the concern of this Library, we can use other plug ins for that so we should save ourselves time for other things.

**Comment by sanity** [comment]
This looks great, should I hold-off before integrating into the codebase?  I can do it if you're not sure of the best place to put it, also happy to merge a pull request.

**Comment by DineshSolanki** [comment]
@sanity I'm happy to have you do it, what's your take on it @frnknglrt ?

**Comment by sanity** [comment]
Just thinking, classes could go in a new `kweb.html.fileUpload` package, with the `fileInput` extension function going in `prelude.kt` so it's imported by default.

**Comment by sanity** [comment]
I will add it if @frnknglrt is ok with that.

**Comment by DineshSolanki** [comment]
Yes, that will be fine, untill then @frnknglrt might be here,

**Comment by sanity** [comment]
Let's see, I'll probably switch it from using Kotson/Gson to Kotlin serialization, eventually I want to remove the Gson dependency from Kweb as Kotlin serialization is faster and Gson is no-longer maintained.

**Comment by sanity** [comment]
Ok, should be ready to merge, if you wouldn't mind trying it out first you can do so by modifying your build.gradle:

```groovy
	        implementation 'com.github.kwebio:kweb-core:issue-165-FileReader_API_Support-SNAPSHOT'
```

**Comment by frnknglrt** [comment]
Thanks, I really appreciate this merge request.

I thought about how kweb will move forward with the file upload component without breaking the api. When we merge it, the api shall be stable so that kweb users can easily upgrade to newer versions. I came to the conclusion that the following potential reasons for change may or may not exist somewhere down the road.

1. Chunked upload for large files. E.g. if someone wants to Upload a 1GByte file. However, this can be implemented transparently for the kweb users by changing the JavaScript and sending multiple small pieces instead of one single message containing the whole file. On the server side we‘d need to provide some Output Stream in addition to the base64Content of the FileUpload. But if I don‘t miss anything this can be added later without changing the Api by providing a getter for base64Content. So, no issue if anyone wants that change in the future.

2. Extending the api to provide feedback on the progress of a file upload. This may be more important as it seems as a file upload over a slow link basically freezes the connection between the browser and the server. With other words: during a file upload, the backend may not be able to receive other inputs or events from the web browser. However, I never had any such problems here and 1) would also solve that issue should it ever become a problem. Slow uploads will most likely happen on mobile phones. Kweb is much more interesting for that use case than it seems as the resulting page size is significantly lower for kweb than nearly all single page apps written nowadays.

**Comment by sanity** [comment]
Great, released in [0.7.33](https://github.com/kwebio/kweb-core/releases/tag/0.7.33), will close this issue for now.

**Comment by DineshSolanki** [comment]
@sanity we should remove the code `input.inputElement.setAttributeRaw("hidden", true)` from the sample, I hid it because I used another button to click it. and forgot to remove that line when posting here.

**Comment by sanity** [comment]
@DineshSolanki No problem, I have removed it from `master` and the release notes, which will update the API docs.
