### ISSUE TITLE
JDK 8 issue

### ISSUE THREAD

**Issue by mkit** [kwebio/kweb-core#167]
Hi
I am seeing the following error printout when running with jdk8. Is this normal?

'''
20:19:03.978 [main] DEBUG org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory - Could not initialize org.eclipse.jetty.alpn.openjdk8.server.OpenJDK8ServerALPNProcessor@6404f418
java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN
'''

**Comment by sanity** [comment]
Hmm, I'm not sure what that's about - looks like it could be a [Ktor](https://ktor.io/) issue.  The fact that it's logged at `DEBUG` suggests that it's low-priority, but it might be worth submitting an issue to Ktor to confirm.

**Comment by mkit** [comment]
Thank you.
