### ISSUE TITLE
Allow customizing the "<noscript>" tag

### ISSUE THREAD

**Issue by MrPowerGamerBR** [kwebio/kweb-core#171]
**Is your feature request related to a problem? Please describe.**
By default Kweb shows `This page is built with <a href="https://kweb.io/">Kweb</a>, which requires JavaScript to be enabled.` if JavaScript is disabled.

It would be nice if you are able to change that text, or maybe dynamically provide it (example: locales)

**Describe the solution you'd like**
An option would to move [this](https://github.com/kwebio/kweb-core/blob/f1a9ae5f856ffd3da146dcf3b7b753e55d91762e/src/main/kotlin/kweb/html/HtmlDocumentSupplier.kt#L30) to a plugin that is automatically registered in Kweb, then add a way to disable that plugin. 😊 

**Describe alternatives you've considered**
Looking at the source code to see if it is possible to change it, but doesn't seem like it is possible.

**Additional context**
Nothing here... yet!

**Comment by sanity** [comment]
This should be doable with a plugin by overriding the [decorate()](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/plugins/KwebPlugin.kt#L13) function.

This provides access to the HTML document via the [Jsoup HTML parser](https://jsoup.org/), from there modifing the <noscript> should be easy.

**Comment by MrPowerGamerBR** [comment]
Yeah, looks like it was easier than I thought!

```kotlin
class KwebPluginReplaceNoScript : KwebPlugin() {
    override fun decorate(doc: Document) {
        super.decorate(doc)
        doc.selectFirst("noscript")
                .text("Text here")
    }
}
```

(I think it would be nice if that was added to the documentation as an "example of what you can do with Kweb plugins") 😊

**Comment by sanity** [comment]
Agreed, if you'd like to submit a pull request for a new KwebPlugin I'll be happy to merge. Might be worth using `innerHtml` rather than `text` for more flexibility.
