### ISSUE TITLE
"url.value = ..." doesn't refresh with Ktor routing / Can't use Ktor routing with multi page applications

### ISSUE THREAD

**Issue by MrPowerGamerBR** [kwebio/kweb-core#172]
This is not really a "bug" because I think this is intentional/can't fix, but it is not obvious how this is possible to do.

This works fine
```kotlin
    Kweb(port = 16097) {
        doc.body {
            route {
                path("/") {
                    url.value = "/number/1"
                }
                path("/number/{num}") { params ->
                    val num = params.getValue("num").toInt()
                    a().text(num.map {"Number $it"}).on.click {
                        num.value++
                    }
                }
            }
        }
    }
```

And this is a similar code, but using Ktor + Kweb    
```kotlin
        routing {
            get("/") {
                call.respondKweb {
                    doc.body {
                        url.value = "/number/1"
                    }
                }
            }

            get("/number/{num}") {
                call.respondKweb {
                    doc.body {
                        val num = KVar(call.parameters["num"]!!.toInt())

                        a().text("Number ${num.value}").on.click {
                            num.value++
                        }
                    }
                }
            }
        }
 ```
 
And while the first one works fine (the page magically refreshes without a full page refresh), the second one changes the URL but the page content doesn't change at all.

I think the solution would be to use `respondKwebRender` and use the routing there, but then you are kinda "ignoring" Ktor's routing (since you just use a wildcard path in Ktor) and using Kweb's routing... which doesn't look very good because it looks kinda wonky.

**Comment by sanity** [comment]
Yes, this behavior is expected. Ktor routing and Kweb routing are quite different and can't be used interchangeably because Kweb routing needs to be able to redraw pages without doing a full reload when the URL changes.

**Comment by MrPowerGamerBR** [comment]
Yeah that makes sense (which was what I thought, that Kweb wouldn't be able to route).

Thanks for the response 😊
