### ISSUE TITLE
Element.onImmediate.click executes immediately instead of after event.

### ISSUE THREAD

**Issue by nanodeath** [kwebio/kweb-core#179]
**Describe the bug**
The callback in `Element.onImmediate.click {}` appears to execute immediately, on load, instead of waiting for the click event.

**To Reproduce**
Follow the documentation here: http://docs.kweb.io/en/latest/events.html#immediate-events

```kotlin
doc.body {
    val label = h1()
    label.text("Click Me")
    label.onImmediate.click {
        label.text("Clicked!")
    }
}
```

**Expected behavior**
An h1 tag is displayed with text "Click Me", and when clicked, the text changes to "Clicked!" instantaneously without a round-trip to the server.

**Actual behavior**
An h1 tag is displayed with text "Clicked!". Clicking on it does nothing. Restarting the server doesn't change anything, nor Ctrl-F5 in the browser (Firefox 85.0.1 Linux).

**Version**
0.8.6

**Comment by sanity** [comment]
Fixed in 0.8.8 release, including a unit test to catch any future regression.
