### ISSUE TITLE
JQueryCorePlugin Element#executeOnSelf doesn't work with Document.Body

### ISSUE THREAD

**Issue by BreadMoirai** [kwebio/kweb-core#182]
**Describe the bug**
JQueryCorePlugin.kt declares an extension function `Element#executeOnSelf` which uses the element id to select and run js
```kotlin
fun Element.executeOnSelf(js: String) {
    execute("$('#$id')$js")
}
```
This however, does not work with document.body since that html tag is not assigned an id and so it is evaluated to
```js
$('#null')...
```

**To Reproduce**
```kotlin
document.body.executeOnSelf(".position()")
```
will result in 
```js
Executed JavaScript $('#null').position()
undefined
```

**Expected behavior**
`#executeOnSelf` should be able to properly query the document body

**Comment by Derek52** [comment]
I've just released version 0.8.7 that fixes this.
