### ISSUE TITLE
Session-Stickyness behind load balancer

### ISSUE THREAD

**Issue by frnknglrt** [kwebio/kweb-core#191]
**Is your feature request related to a problem? Please describe.**
Today i debugged a repeated reload cycle due to an error establishing the websocket connection. The exception was as follows:

`java.lang.IllegalStateException: Unable to find server state corresponding to client id DcVM2b`

It turned out that our load-balancer caused the websocket-connection and the initial page load to end up at separate kweb instances, thus instance A was not aware of the state at instance B. 

Solution was straight forward: Enable session affinity at our haproxy.

**Describe the solution you'd like**
As it took me some minutes to figure out that problem, it may be worth to add that potential error class to the FAQ, so that other users are aware of that requirement.

**Describe alternatives you've considered**
Implement a session storage so that multiple kweb instances share the same state. However, i dislike that solution.

**Comment by frnknglrt** [comment]
Proposed text for the FAQ
====================

**Question: I want to deploy a KWeb Application behind a load balancer. What do i need to consider?**
Please make sure to enable session affinity so that repeated requests from the same client end up at the same kweb instance. Kweb does not share it's internal state between multiple instances, so it is important to make sure that each request from a single user ends up at always the same instance. 

If the load balancer uses e.g. round robin strategy for load balancing, repeated requests end up at different backend instances and kweb may not function propery. 

Example how to setup HAProxy can be found [here](https://www.haproxy.com/de/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/)

**Comment by sanity** [comment]
Thank you, I have added this Q/A to the [FAQ](http://docs.kweb.io/en/latest/faq.html) :)
