### ISSUE TITLE
[Question] Desktop Application with Kweb

### ISSUE THREAD

**Issue by AnTyVik** [kwebio/kweb-core#205]
Is it possible to create a desktop application based on Kweb? Roughly same way as done with Electron (running in browser/web view) but using Kweb/Kotlin instead.

**Comment by sanity** [comment]
Yes, absolutely - that's one of the use cases I had in mind when designing Kweb. 

It should also be possible to use [Graal Native Image](https://www.graalvm.org/reference-manual/native-image/) to produce a smaller self-contained binary for your app.

**Comment by AnTyVik** [comment]
Are there any documentation on this topic? (I wasn't able to find it but it doesn't mean it not exists :smile: ) Or maybe you can suggest a way to get some understanding. Would be highly appreciated :slightly_smiling_face:

**Comment by sanity** [comment]
I don't think we have documentation on this specifically but it shouldn't be significantly different from building any other website with Kweb, except it will need to be bundled with something like Electron. Is there a particular part of it that you're unsure about?

**Comment by AnTyVik** [comment]
I thought Kweb have ability to create desktop apps on its own (without Electron). I just don't want to enlarge app with Electron

**Comment by sanity** [comment]
Well, you don't need to use Electron, it can work with any normal web browser, it's just if you want it to look like a standalone app you'll need to use something like Electron or a lighter-weight alternative.
