### ISSUE TITLE
Is there any specific reason why classes() function can not be used with a KVar(String) like text()?

### ISSUE THREAD

**Issue by geomagilles** [kwebio/kweb-core#208]
It would be useful to update design based on state (like Vue or React)

**Comment by sanity** [comment]
Good idea, the next release of Kweb will support this.

In the meantime you can use `Element.setAttribute("class", kvar)`.

**Comment by sanity** [comment]
Released in `0.10.1`.

**Comment by geomagilles** [comment]
> Released in `0.10.1`.

It was quick - thx!
