### ISSUE TITLE
How to: manage session?

### ISSUE THREAD

**Issue by geomagilles** [kwebio/kweb-core#211]
KWeb has a great potential. But I miss examples on how to do the usual stuff. For example, It's not clear from the documentation which state of the server is shared among every client.

In particular, how to get separate sessions as a classical website with login?

**Comment by sanity** [comment]
We definitely need more comprehensive examples illustrating best practices for things like user management.

Kweb gives full access to both [local](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/html/Document.kt#L58) and [session](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/html/Document.kt#L64) storage via `Doc.localStorage` and `Doc.sessionStorage`, but currently you need to build your user auth on top of those.

**Comment by geomagilles** [comment]
Thx - I'm new with ktor, but is there a way to reuse ktor implementation?

**Comment by frnknglrt** [comment]
Hello, 

I will conduct an example this evening

Viele Grüße,

Frank

**Comment by sanity** [comment]
@frnknglrt Thank you, that would be great :) Would [kweb-demos](https://github.com/kwebio/kweb-demos) be the right place for it?

**Comment by frnknglrt** [comment]
I’ll make you a pull request there 

Viele Grüße,

Frank

**Comment by geomagilles** [comment]
I just did a starter template with a menu and a few routes - based on tailwind. Btw it's a great framework to use with Kweb. It took me a few days. It's not that long but can be discouraging. The main issue is that there is plenty of ways of doing it - the lack of guidelines is an issue

**Comment by sanity** [comment]
@geomagilles I'll check out tailwind.

To your second question, Kweb is released under the [LGPL](https://github.com/kwebio/kweb-core/blob/master/LICENSE), which is a "non-viral" license. In summary, you can build on Kweb and distribute whatever you build, but if you modify Kweb and wish to distribute that modified version, you must make the modified source for Kweb available. You may find [this FAQ](https://www.gnu.org/licenses/gpl-faq.en.html) helpful.

Best of luck with your project, please let us know how you get along :)

**Comment by geomagilles** [comment]
I see the PR in kweb-demos. It's a great start. 

Honestly, I state again that KWeb has great potential, but we need more libraries to extend the framework (like kweb-auth for authentification, kweb-router for routing, maybe kweb-template for templating ...) or alternatively a clear way to use existing ktor developments.

Btw, keep the good works and congrats!
