### ISSUE TITLE
Inlined svg "disappearing" when re-rendered 

### ISSUE THREAD

**Issue by geomagilles** [kwebio/kweb-core#215]
**Describe the bug**
https://www.loom.com/share/34e19d5b30ff4212a1318fa296be7d8b

**To Reproduce**
the svg disappears only when I re-render a component, not at the initial rendering

**Comment by geomagilles** [comment]
example to reproduce, 
```
render(counter) {
    div().text(counter)
    div().new {
        // insert svg here
    }
}
```
and 
```
while(isActive) { counter.value++; delay(1000 } 
```

**Comment by geomagilles** [comment]
may be related: https://webhint.io/docs/user-guide/hints/hint-create-element-svg/

**Comment by sanity** [comment]
Ah, very interesting - looks like we should probably be using `createElementNS` for element creation, allowing the namespace to be configurable but defaulting to `http://www.w3.org/1999/xhtml`. Should be a simple change.

**Comment by sanity** [comment]
Was thinking about this.

I think we need to add a namespace parametmer to `ElementCreator.create`, defaulting to HTML, but where other options can be specified.

@geomagilles My question is whether descendant elements should inherit their parent's namespace, rather than defaulting back to HTML.

Since you've been working with [SVG], any thoughts?

**Comment by geomagilles** [comment]
I'm not at all DOM specialist - but from a user perspective, I would create a dedicated `svg()` element for which the right namespace would be applied. I've found this example:
```
function CreateSVG() {
    var xmlns = "http://www.w3.org/2000/svg";
    var boxWidth = 300;
    var boxHeight = 300;

    var svgElem = document.createElementNS(xmlns, "svg");
    svgElem.setAttributeNS(null, "viewBox", "0 0 " + boxWidth + " " + boxHeight);
    svgElem.setAttributeNS(null, "width", boxWidth);
    svgElem.setAttributeNS(null, "height", boxHeight);
    svgElem.style.display = "block";

    var g = document.createElementNS(xmlns, "g");
    svgElem.appendChild(g);
    g.setAttributeNS(null, 'transform', 'matrix(1,0,0,-1,0,300)');

    // draw linear gradient
    var defs = document.createElementNS(xmlns, "defs");
    var grad = document.createElementNS(xmlns, "linearGradient");
    grad.setAttributeNS(null, "id", "gradient");
    grad.setAttributeNS(null, "x1", "0%");
    grad.setAttributeNS(null, "x2", "0%");
    grad.setAttributeNS(null, "y1", "100%");
    grad.setAttributeNS(null, "y2", "0%");
    var stopTop = document.createElementNS(xmlns, "stop");
    stopTop.setAttributeNS(null, "offset", "0%");
    stopTop.setAttributeNS(null, "stop-color", "#ff0000");
    grad.appendChild(stopTop);
    var stopBottom = document.createElementNS(xmlns, "stop");
    stopBottom.setAttributeNS(null, "offset", "100%");
    stopBottom.setAttributeNS(null, "stop-color", "#0000ff");
    grad.appendChild(stopBottom);
    defs.appendChild(grad);
    g.appendChild(defs);

    // draw borders
    var coords = "M 0, 0";
    coords += " l 0, 300";
    coords += " l 300, 0";
    coords += " l 0, -300";
    coords += " l -300, 0";

    var path = document.createElementNS(xmlns, "path");
    path.setAttributeNS(null, 'stroke', "#000000");
    path.setAttributeNS(null, 'stroke-width', 10);
    path.setAttributeNS(null, 'stroke-linejoin', "round");
    path.setAttributeNS(null, 'd', coords);
    path.setAttributeNS(null, 'fill', "url(#gradient)");
    path.setAttributeNS(null, 'opacity', 1.0);
    g.appendChild(path);

    var svgContainer = document.getElementById("svgContainer");
    svgContainer.appendChild(svgElem);
}
```
from https://stackoverflow.com/questions/3492322/javascript-createelementns-and-svg

But I feel that I may be more opinionated than you regarding Kweb! (I feel the framework should take more decisions itself for making the dev life easier). For a unopiniated way of doing, you could add a namespace parameter to ElementCreator.create. My understanding (and the example above) is that internal elements should inherit of it.

**Comment by geomagilles** [comment]
Yes - but stupid question: how do you test locally? On Infinitic, I can publish to mavenLocal() and require a snapshot version in my test project, but I  do not see something equivalent on yours

**Comment by geomagilles** [comment]
also regarding your suggested syntax, it appears strange to me as it seems to imply that the content of the `div` has a namespace, while the namespace actually applies to the svg element. For exemple the `div` could have 2 internal elements: a `a` followed by a `svg` - only the svg should have the namespace

**Comment by sanity** [comment]
Re: testing locally, I normally write a unit test and run it from within the kweb project itself - so no need to deploy to a maven repo.

I see your point re: the namespace, does that suggest that `namespace` should be a parameter to `element()`? Should child elements inheret the namespace, or should it be specified explicitly for each element?

**Comment by geomagilles** [comment]
a good side-effect of using the `maven-publish` plugin is to have a task "publishToMavenLocal" that let you publish your lib in a local maven repo. It's very convenient to use a working version into another local project.

Yeah - at the end, it seems a `namespace` property to `element()` and `setAttribute()` functions may be enough to handle those cases (without inheritance)

**Comment by geomagilles** [comment]
@sanity - the current implementation works. Still It appears to me cleaner to have the namespace property in `element()` and `setAttribute()` functions

**Comment by sanity** [comment]
Agreed, will try to implement that this weekend.

**Comment by sanity** [comment]
Should be fixed in `0.10.9`.

**Comment by frnknglrt** [comment]
Hello, 

sorry to post to an old discussion: I'd also like to embed an svg content that was generated by [lets-plot-kotlin](https://github.com/alshan/lets-plot-mini-apps/blob/main/jvm-plot-export/src/main/kotlin/DemoUtil.kt). I did quite alot with KWeb already, but this one seems tricky. I see the following means to reach the result:

1. Base64-Encode the image and put it as data url into the image tag. That's what i usually do with images that are generated on the fly or retrieved from internal systems. CON: This solution is very hands on but we loose a bit of the seamless composability of KWeb i really like very much. The SVG has to be encoded and pasted to a data url and we bypass the kotlin typesytem and its ability to catch common errors. 
2. Create a specific element where i can dump the SVG as a part of the dom. Then, it may be even possible to manipulate the image partially. Most likely i need to parse the SVG from lets-plot and copy it over to the KWeb elements. I'm not sure how light-weight the second solution is. Maybe it won't work well for bigger svgs. Also i'm too lazy to implement that. 
3. Add a small functionality to dump chunks of markup directly to the dom. This can for sure be achieved using a small JS extension. Maybe CON: It's just a gut feeling but i dislike having too wrap content in javascript for delivering it to the browser. Of course it won't be horribly inefficient, i just dislike using JS for that purpose.  
4. Write an good old ktor endpoint which returns the SVG. For sure i won't do that. CON: I don't like it. With that approach all the functionality is scattered around different components/pieces of code. 

Other factors to consider: 
Caching: Approach 1-3 are virtually impossible to cache on the client-side. If the SVG is within a render-block it may be reloaded frequently. Maybe that's not necessary if the SVG is static or semi-static.


Are there any other ideas how that can be done nicely? 

BR

Frank

**Comment by geomagilles** [comment]
I see 2) as the more idiomatic way - but it may request a manual conversion for each SVG or a tool like described in #217

**Comment by frnknglrt** [comment]
Good evening, 

i just found that ticket. Now over half an year later i may provide some feedback with regard to that one. I went with the following solution: 

```
val contentSvg = PlotSvgExport.buildSvgImageFromRawSpecs(p1.toSpec()) // returns a string
val dataUrl = "data:image/svg+xml;base64,"+ Base64.getEncoder().encodeToString(contentSvg.toByteArray())   img(mapOf("src" to JsonPrimitive(dataUrl), "width" to JsonPrimitive(800), "height" to JsonPrimitive(450)))
```

It turned out to be an sufficient solution. It never made any troubles. As this ticket was reopened due to my comment, i now deliberately close that ticket.
