### ISSUE TITLE
Browser history does not work forward

### ISSUE THREAD

**Issue by geomagilles** [kwebio/kweb-core#219]
**Describe the bug**
the browser history works backward (clicking the back button led to previous url) but no forward ( the current url always appear as the last one)

**To Reproduce**
Any site with routing

**Expected behavior**
I should be able to navigate backward and forward

**Comment by sanity** [comment]
Relevant: https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event

**Comment by sanity** [comment]
Fix released in `0.10.11`.
