### ISSUE TITLE
Publishing to MavenCentral()

### ISSUE THREAD

**Issue by geomagilles** [kwebio/kweb-core#220]
**Is your feature request related to a problem? Please describe.**

Will you consider publishing to MavenCentral? 

When distributing an application using Web, the end-user currently needs to add maven("https://jitpack.io") to their repository. It's an additional layer of complexity / errors.

**Comment by sanity** [comment]
Happy to do it if our use of jitpack is a problem - my impression was that it seemed like a PITA but I could be wrong.

**Comment by geomagilles** [comment]
Yes - it can be a pain to setup. But easy once done. 
- I've found this article very useful https://proandroiddev.com/publishing-a-maven-artifact-3-3-step-by-step-instructions-to-mavencentral-publishing-bd661081645d
- as well as this example https://github.com/sksamuel/hoplite/blob/master/publish.gradle.kts

**Comment by sanity** [comment]
I've filed the Jira issue to start this process.

**Comment by sanity** [comment]
I spent quite a while trying to set this up but it's extremely convoluted. Sticking with Jitpack until a better solution is available.
