### ISSUE TITLE
How to add favicons

### ISSUE THREAD

**Issue by geomagilles** [kwebio/kweb-core#225]
**Is your feature request related to a problem? Please describe.**
when requesting /favicon.ico I get `favicons not currently supported by kweb` - why not letting users add favicons?

**Describe the solution you'd like**
Being able to add favicons

**Comment by sanity** [comment]
Here is a proposed implementation, thoughts?

```kotlin
 val config = object : KwebDefaultConfiguration() {
            override suspend fun faviconIco(call: ApplicationCall) {
                call.respondBytes(
                    // Here the favicon.ico file is read from a resource
                    this::class.java.getResourceAsStream("favicon.ico").readAllBytes(),
                    ContentType("image", "x-icon"),
                    status = HttpStatusCode.OK
                )
            }
        }

        Kweb(port = 1245, kwebConfig = config) {
            // ...
        }
```

**Comment by geomagilles** [comment]
TBH, I'm not sure to understand why there is a need for a special setup for favicon.ico or robots.txt. I would expect to put them in a static folder to be able to serve them (and there is more than a single favicon.ico to consider - https://sympli.io/blog/heres-everything-you-need-to-know-about-favicons-in-2020 )

**Comment by sanity** [comment]
Good question. I was trying to offer something better than the current 404s in as flexible a way as possible. Kweb may be a relatively small component of a large piece of software, so I'd prefer to keep it decoupled from the filesystem.

**Comment by geomagilles** [comment]
I think I see - If I make an analogy with Vue.js, maybe it means we need specific libraries kweb-* for extended use-cases.

**Comment by kokorins** [comment]
Hi, I'm using next approach.
serve static files from resource folder: https://github.com/kwebio/kweb-core/pull/78
and then 
```
fun ElementCreator<HeadElement>.favicon(pagePath: String, type: String? = null) {
    val localType = type ?: pagePath.split(".").lastOrNull()
    element(
        "link", mapOf(
            "rel" to "icon".json,
            "type" to "image/$localType".json,
            "href" to pagePath.json
        )
    )
}
```
