### ISSUE TITLE
Kweb Apps don't work on Xiaomi Mi Browser (Android)

### ISSUE THREAD

**Issue by frnknglrt** [kwebio/kweb-core#284]
**Describe the bug**
We found an ugly bug in kweb. Web pages made with kweb don't work on Xiaomi phones when the Mi Browser is used. More precisely, the pages load correctly and are rendered correctly but it is impossible to interact with the web page. 

When interacting with the web page, e.g. by pressing a button, KWeb produces the following error message: 

```
[ERROR] 2022-08-16T12:15:25.976 Y2rF_y 7866b20abcdc7211c4c69f62  [qtp1337192014-199] kweb.Kweb: Exception while receiving websocket message kotlinx.serialization.json.internal.JsonDecodingException: Failed to parse 'int'\nJSON input: .....hiftKey":false,"type":"click","x":193.8181915283203,"y":476}\n	at 
kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)\n	at 
kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)\n	at 
kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.unparsedPrimitive(TreeJsonDecoder.kt:145)\n	at 
kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedInt(TreeJsonDecoder.kt:368)\n	at 
kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedInt(TreeJsonDecoder.kt:35)\n	at 
kotlinx.serialization.internal.TaggedDecoder.decodeIntElement(Tagged.kt:251)\n	at 
kweb.html.events.MouseEvent$$serializer.deserialize(events.kt:40)\n	at 
kweb.html.events.MouseEvent$$serializer.deserialize(events.kt:40)\n	at 
kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)\n	at 
kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)\n	at 
kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)\n	at 
kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)\n	at 
kweb.html.events.OnReceiver$event$2.invoke(OnReceiver.kt:38)\n	at 
kweb.html.events.OnReceiver$event$2.invoke(OnReceiver.kt:30)\n	at 
kweb.html.events.OnReceiver$event$1.invoke(OnReceiver.kt:21)\n	at 
kweb.html.events.OnReceiver$event$1.invoke(OnReceiver.kt:20)\n	at 
kweb.Element$addEventListener$1.invoke(Element.kt:473)\n	at kweb.Element$addEventListener$1.invoke(Element.kt:471)\n at 
kweb.Kweb.listenForWebsocketConnection(Kweb.kt:290)\n	at 
kweb.Kweb.access$listenForWebsocketConnection(Kweb.kt:42)\n	at 
kweb.Kweb$listenForWebsocketConnection$1.invokeSuspend(Kweb.kt)\n	at 
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n	at 
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)\n	at 
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)\n	at 
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)	at
java.base/java.lang.Thread.run(Unknown Source)
```

In KWeb the MouseEvent has property `x` defined as int but the Mi Browser submits it as float. According to Mozilla, the specification of this event also states that it shall be a float. Nevertheless, submitting positions as fractions of pixels is pointless and i've not seen it on another browser. 

**To Reproduce**
1. Install MI Browser on Android phone from google play. 
2. Open TodoApp on a Mi browser. No button is clickable.

**Expected behavior**
KWeb Apps shall work on Mi Browser as well. 

**Proposed fix**

1. I will send a pull request solving that problem. That PR will change the definition of `MouseEvent`. This may break the compatibility but then pages also work on the MI Browser which is important for me. 
2. Unfortunately, it was a little bit difficult to fix this problem as it caught us in prod and kweb happily eats the exception away in  the `listenForWebsocketConnection` function. Thus i expose an extension point so that application specific logging solutions can be plugged in an catch such exceptions. Currently, the error is logged but it is impossible to react to such errors or customize the behavior. 
3. `kweb_bootstrap.js` in function `debugErr` throws an exception if an client exception happens and no debug mode is active. This breaks also the websocket connection if kweb debug mode is disabled. I'd suggest removing the exception throwing part if debug is disabled. Here a logging is sufficient to NOT break the client. 

Please feel free to merge the pr i will send soon.

**Comment by frnknglrt** [comment]
That was fast.... wow

**Comment by sanity** [comment]
I aim to please :)

Was that exception being swallowed because you didn't have a logger set up? Swallowed exceptions are really nasty, need to avoid.
