### ISSUE TITLE
ktor FeatureApp example not working for ktor 2.0.0+ 

### ISSUE THREAD

**Issue by GenerRR** [kwebio/kweb-core#290]
hello, im not sure where to ask about this, 
but it seems that Ktor plugin api changed after its 2.0.0 version (tried with 2.1.1),
how to correctly install Kweb into existing 2.0.0+ Ktor porject now?

im also noticed that chart plugin is no longer in list of builtin Kweb plugins, should i rely on existing js chart libs ? (and why decided to remove it from Kweb ?)
it whould be very nice to have a very simple chart project among existing kweb examples

**Comment by sanity** [comment]
This is on our todo list, should be able to fix in the next few days.

**Comment by Derek52** [comment]
#292 fixes this. Kweb v0.12.0 is now using Ktor 2.1.1.
