### ISSUE TITLE
Migrate to Gradle 7

### ISSUE THREAD

**Issue by Derek52** [kwebio/kweb-core#304]
Upgrading to the latest version of Gradle would be great, but, Gradle 7 breaks the testing suite.
I ran `./gradlew wrapper --gradle-version 7.5.1` to upgrade the Gradle version. I also tried version `7.0` and a few intermediary versions.

Running Kweb's tests after upgrading to Gradle 7+ do not work. 15-20 of the tests are ignored, and at least one will fail with an error that looks like `Received a completed event for test with unknown id '1.4'. Registered test ids: '[1.1, 1.2, 1.7, 1.6, 1.9, 1.8, :test]'`

This appears to be a concurrency issue. Seeing as how the tests work with Gradle 6.9.2, I believe the concurrency issue is caused by Gradle. It is possible that the tests could be re-written in a way that makes them play nicely with Gradle 7, but If that is even possible, I'm not sure how it would be done.

I tried several work arounds that involve configuring Gradle or Junit differently, but these didn't work. They were in [this Github thread](https://github.com/gradle/gradle/issues/6453). Specifically [this](https://github.com/gradle/gradle/issues/6453#issuecomment-415780499) and [this](https://github.com/gradle/gradle/issues/6453#issuecomment-463702749) comment.

Another fix that was suggested was to go into IntelliJ settings and use the Intellij test runner instead of Gradle's. This wouldn't make the tests work in Github's CI tools, so I don't think it's a good fix. It also didn't work for me testing locally on my machine anyway.

**Comment by frnknglrt** [comment]
Hello,

we recently updated another project to gradle 7. It was a huge task but it turned out to provide some unexpected benefits.

So I’m a big fan of porting kweb to gradle 7. 

Regarding the issues: did you try to disable the parallel execution of the tests? Maybe I find some minutes this evening to also have a look at the code. Did you push the branch or do you have a fork where I  can see your changes?

BR

Frank

**Comment by Derek52** [comment]
I have a pr here, https://github.com/kwebio/kweb-core/pull/303. The most recent commit is reverted to Gradle 6.9.2. But, all other dependencies are on the latest version, and I rewrote the tests to use the newest Selenium API

**Comment by Derek52** [comment]
I changed the `test` block in `build.gradle` to this
`test {
    useJUnitPlatform()
    systemProperty('sel.jup.default.browser', System.getProperty('sel.jup.default.browser'))
    systemProperty('junit.jupiter.execution.parallel.enabled', false)
    maxParallelForks = 1
}`

to attempt to disable parallel execution of tests. This did not solve any of the problems I was encountering.

**Comment by tcrawford-figure** [comment]
Hi @Derek52, please see my PR https://github.com/kwebio/kweb-core/pull/305 which updates to gradle 7.5.1 and migrates to kotest from kotlintest. I believe the migration from kotlintest to kotest is the primary reason that everything started working, but I can't 100% confirm that belief. It may have been that migration among a few other things I did.

**Comment by sanity** [comment]
Fixed #305
