### ISSUE TITLE
Update handling of the Fomantic-UI dependency

### ISSUE THREAD

**Issue by aSemy** [kwebio/kweb-core#323]
**Is your feature request related to a problem? Please describe.**

When I see the kweb-core project on GitHub, it tells me that it's a CSS project, which is odd!

<img width="519" alt="image" src="https://user-images.githubusercontent.com/897017/194945036-6b30f79d-8606-465e-b49b-cc08ded708dc.png">

This is because of a large number of Formantic-UI themes

<img width="400" alt="image" src="https://user-images.githubusercontent.com/897017/194945236-19cda7a2-ab07-443e-be55-9ae654be63b5.png">

**Describe the solution you'd like**

I see two options

1. the files are stored in a zip, which is committed to the repository. A Gradle task will, on demand, unzip the file and add it to the main source set (pro: more stable, con: have to manually update the zip)
2. [Define a repo for downloading artifacts from GitHub](https://stackoverflow.com/questions/23023069/gradle-download-and-unzip-file-from-url/34327202#34327202), and define Formantic-UI repo as a dependency (pro: automatic versioning & downloading, con: what happens if the GitHub release is deleted?)

**Describe alternatives you've considered**

Leave it as-is.

**Additional context**

**Comment by sanity** [comment]
I think this may solve that problem: https://stackoverflow.com/a/43520676

I've added the `.gitattributes` file, not sure how often Github updates those stats.

**Comment by aSemy** [comment]
That looks like it's worked! 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/897017/194950621-6463d412-3947-4f5d-8fe1-718160e7b90d.png">
