### ISSUE TITLE
Parent element inside ElementCreator class

### ISSUE THREAD

**Issue by chandrin94** [kwebio/kweb-core#335]
I noticed that since version 0.12.7, the `parent` element inside `ElementCreator` class has become an internal variable, so it is no longer externally accessible. This change can be breaking, since implementations that accessed this `parent` element inside the `ElementCreator` class are now obsolete. For example, if somone overrides the `Element` class, and the overriding class contains an `ElementCreator` item instead of an `Element` item, the `parent` variable can no longer be passed as a constructor argument.

Could the `internal` modifier from the `parent` element be removed ?

Any other suggestions are of course welcome.

![Screenshot from 2022-10-15 16-22-03](https://user-images.githubusercontent.com/81678661/195988700-c25e4377-14f4-46bf-ac1f-66351c9dc31a.png)

**Comment by sanity** [comment]
Thanks for the report, this problem should be fixed in current `master` branch, would you mind testing to verify?

```
implementation 'com.github.kwebio:kweb-core:21326fba15'
```

Note that `parent` is now deprecated, `element` is preferred.

**Comment by sanity** [comment]
Should be fixed in 1.0.0-rc.1

**Comment by chandrin94** [comment]
Yes it is now fixed, thank you and sorry for my late reply.

**Comment by sanity** [comment]
You're welcome, I've now added an API compatibility check which should prevent breaking API changes going forward (unless deliberate).
