### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by NeonSalamander** [kwebio/kweb-core#36]
Hello everyone, is there an example with authentication?

**Comment by sanity** [comment]
@primaldevelop Apologies, I'm afraid not yet, as of right now you'll need to roll your own.  If you're interested in tackling this let me know, I have some ideas about a good approach :)

**Comment by sanity** [comment]
Just researching, found this: https://auth0.com/

It looks great but unfortunately they charge about $0.01/user/month, which will be a dealbreaker for many.

**Comment by sanity** [comment]
According to Reddit this may be a good source of inspiration: http://www.passportjs.org/

**Comment by samgarasx** [comment]
I think you can use [Ktor auth](https://ktor.io/servers/features/authentication.html), and let the developer to use it with a simple DSL to configure the provider and routes to attach preconfgured auth.

**Comment by sanity** [comment]
Just want to keep this open for now.

**Comment by sanity** [comment]
Probably no one-size-fits-all solution to this so probably doesn't belong in kweb-core.
