### ISSUE TITLE
Improve plugin mechanism

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#37]
The current plugin mechanism is simple, but a little kludgy - plugins must implement [KWebPlugin](https://github.com/kwebio/core/blob/master/src/main/kotlin/io/kweb/plugins/KWebPlugin.kt).

This requires a rethink, possibly inspired by [retrofit adapters](https://github.com/square/retrofit/tree/master/retrofit-adapters).

cc: @ammelto

**Comment by ammelto** [comment]
I do like the retrofit adapter approach. I'll look into this after I finish the issue I'm working on now.

**Comment by sanity** [comment]
Closing because plugin system was simplified and improved when adding server-side rendering support several versions ago.
