### ISSUE TITLE
Prefixing all kweb routes

### ISSUE THREAD

**Issue by melike2d** [kwebio/kweb-core#371]
Hello! I recently found this project through Reddit and have decided to try it out in one of my projects but I've hit a roadblock. 

I want to prefix all frontend routes with `/web`, at first I tried using the Ktor Feature with something like the following but it doesn't include the assets or websocket routes
```kt
routing {
    get("/web/{visitedUrl...}") {
        call.respondKweb(buildPage)
    }
}
``` 

My second idea was to just create my own Kweb instance and manually do all of the setup myself but the primary constructor of Kweb is private + there's some stuff I probably missed.

Any thoughts?

**Comment by sanity** [comment]
That will probably require modifications as a number of paths are hardcoded including `/kweb_static` and `/ws` as you mention, but these could be configuration options.

May I ask the reason for prefixing in this way?

**Comment by melike2d** [comment]
> May I ask the reason for prefixing in this way?

My project is an image-hosting server and looking up images is done through `GET /:file_name`. Using something like `/web` as a prefix allows the frontend to have its own 404 page.

**Comment by sanity** [comment]
Gotcha, are you using the same Ktor instance to serve up files?

**Comment by melike2d** [comment]
> Gotcha, are you using the same Ktor instance to serve up files?

Yes I am. Just FYI, it is open source, just go to my repos and you should see it (dev branch is latest)

**Comment by sanity** [comment]
Is it actually necessary to modify all routes (websocket connection, static assets), or just the visited URL route? Static assets are under `/kweb_static`, WebSocket is `/ws` - aren't they unlikely to clash with your other routes?

**Comment by sanity** [comment]
Ok, I added a [urlPathPrefix](https://github.com/kwebio/kweb-core/blob/issue-371-Prefixing_all_kweb_routes/src/main/kotlin/kweb/config/KwebConfiguration.kt#L89) option to KwebConfiguration, hopefully JitPack will let you [try it out](https://jitpack.io/#kwebio/kweb-core/issue-371-Prefixing_all_kweb_routes-SNAPSHOT), can you let me know if that works for you?

**Comment by sanity** [comment]
Closing for now, reopen if this hasn't solved the issue.
