### ISSUE TITLE
Improve code to set attributes on elements

### ISSUE THREAD

**Issue by Derek52** [kwebio/kweb-core#381]
From the documentation, [here,](https://docs.kweb.io/book/dom.html) is code to create an element and assign values to some of it's attributes

```
button { btnEl ->

    with(btnEl) {
        classes("bigbutton")
        this["autofocus"] = true
        text("Click Me!")
    }
}
```
I like this syntax, but I think this line has some room for improvement.
```
this["autofocus"] = true
```

I would like to see it become
```
this[autofocus] = true
```

By having autofocus be a predefined object/value, I can save time by using autofill while typing. It will also be safer, because my IDE would be able to catch a typo. Right now `this["autofcous"] = true` looks ok at a quick glance, but would not work, and I'd be on my own to find my mistake. This problem was solved for Fomantic classes, but, I don't think the solution used there would work here.

One way to fix this would be to make the most commonly used attributes fields in `element` and then making the code look like
```
this.autofocus = true
```

I think the easier way here would be to simply create an object that has the names of the attributes, like this
```
object attributes {
    val autofocus = "autofocus"
    val display = "display"
    val visibility = "visibility"
}
```

and then I could write the original code like
```
this[attributes.autofocus] = true
```

**Comment by sanity** [comment]
This is interesting, I wonder if we could use generics here - something like:

```kotlin
interface Attribute<T : Any> {
  fun toJsonPrimitive() : JsonPrimitive
}

// And then on the Element class:
fun operator <T> set(attribute : Attribute<T>) : T
```
