### ISSUE TITLE
Allow threadsafe list modifications through ObservableList.iterator() and ObservableList.listIterator()

### ISSUE THREAD

**Issue by AndrewCrowe** [kwebio/kweb-core#385]
I ran into this problem calling removeIf on an ObservableList.

You can work around this by calling remove/removeAt on the list directly.

Easiest fix is probably to change the Iterator returned by ObservableList.iterator to track the current index and call applyChanges. Glancing at the code I'd guess MutableListIterator has the same issue

**Comment by sanity** [comment]
Well, I thought I'd solved the problem nicely and then remembered thread safety, I believe solving this in a threadsafe way would be a lot of work for questionable benefit.

So the best solution, for now, is to throw an UnsupportedOperationException if the user attempts to modify the list using the iterator. This will be rolled out in the next release.

**Comment by sanity** [comment]
Feel free to reopen if you're not happy with this solution.

**Comment by AndrewCrowe** [comment]
I don't think I can reopen issues in this repo.

With the change to throw UnsupportedOperationException this wouldn't be a bug anymore, but I'd suggest either making a new issue or turning this one into an enhancement request.

That said, could you explain what the concurrency issue is? I normally assume Iterators aren't threadsafe anyway.

**Comment by sanity** [comment]
@AndrewCrowe Iterators aren't normally threadsafe except with concurrent datastructures like ConcurrentHashMap, so I think people might be forgiven for having that expectation here - I wanted to err on the side of caution because concurrency bugs can be such a PITA.

I'll convert this to an enhancement request.
