### ISSUE TITLE
Allow custom configuration of Ktor to support HTTPS 

### ISSUE THREAD

**Issue by ammelto** [kwebio/kweb-core#39]
What are your thoughts on exposing the kweb ktor builder to the developer so that the user can create their own routes (for like a public API) without having to spin up a new jetty instance. There could be some really interesting Spring/neo4j integrations if we did that. Essentially that would allow the developer to create their webapp on the same application level as their backend and it might also help with the browser caching issue since we'd just have access to a Spring database or whatever the developer is planning on using for a db. 

The alternative to not exposing ktor would basically be http requests between the backend (whatever it's done in) and kweb through http on the same server which is kind of silly.

**Comment by sanity** [comment]
I think the current mechanism allows you to hook into that via the KWebPlugin.appServerConfigurator() method, but it's not pretty.

I think we should expose Ktor, plugins will frequently need to add new routes, for example a plugin that implements Google Captcha would need to establish a route for the callback.

The question it: what is the cleanest and yet most flexible way to give Plugins access to configuring Ktor?

(Unless you don't think this belongs in the plugin mechanism)

**Comment by ammelto** [comment]
Hmm, that's a good question about whether to include it in the plugins. That does sound like the best place for it at first glance. I'll spend some time thinking it over.

**Comment by sanity** [comment]
Yes, I do think you could achieve it right now without modifying Kweb, but the plugin mechanism really does need some attention as I didn't put a huge amount of thought into it.

**Comment by sanity** [comment]
HTTPS is [now supported](https://github.com/kwebio/kweb-demos/blob/master/https/src/HttpsApp.kt) as of several weeks ago.
