### ISSUE TITLE
HTML template support

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#390]
Just jotting the idea down - needs more thought.

User can provide a HTML template to the Kweb constructor:

```html
<HTML>
<HEAD>
  <TITLE>Hi</TITLE>
</HEAD>
<BODY>
<DIV id="tpl1"></DIV>
</BODY>
</HTML>
```

Which can be used as follows:

```kotlin
val myTemplate = JSoup.parse("my_template.html")
Kweb(port = 1234, template = myTemplate) {
  template(id = "tpl1").new {
    p().text("Hello")
  }
}
```

Question:
* Providing the template to the constructor means that there is one template and it must be used for all pages, too restrictive?

**Comment by Derek52** [comment]
Only having access to one template does seem a little restrictive. It'd be useful for bringing in something like a menu bar, that is going to be used on every page, or building a single page app(quite common these days). It would be restrictive for any other use case.

What about just having a Template class that can be created whenever?
```
class Template(val template : "whatever type JSoup.parse returns") {
    constructor(val htmlFile : String) : this(JSoup.parse(htmlFile))
}
```

The concerns here would be

- Is there a reason we can't call JSoup.parse() after initializing Kweb? Is it too resource intensive?
- Making sure the template is only loaded when the object is created.
- Making sure the template, and modifications to the template(like you adding the `p` tag in your code example) play nicely with kweb's render logic.

Those last 2 points might already work automatically.
