### ISSUE TITLE
clientState in Kweb.kt

### ISSUE THREAD

**Issue by chandrin94** [kwebio/kweb-core#399]
Hello,

i noticed that since version [1.0.1](https://github.com/kwebio/kweb-core/releases/tag/1.0.1) the `clientState` in `Kweb.kt` line 140 is now a private val, instead of public. 
This is a breaking change when someone wants to persist the client state info on shutdown, or access it for any other purpose.

Is this deliberate, and if yes, is there an alternative ?

**Comment by sanity** [comment]
This wasn't deliberate although I hadn't anticipated that people would do this. Was this working for you prior to 1.0.1?

If so, I can reenable or provide an alternative.

**Comment by chandrin94** [comment]
Thanks for the quick reply. 

Yes we were using the client ids from the `clientState`.

**Comment by sanity** [comment]
Ok, I will make it public again and do a new release, but it should be considered fragile. I'll add a Kdoc to this effect.

Would you mind elaborating on how you're using it? eg. what are you using the client ids for?

**Comment by sanity** [comment]
[1.2.1](https://github.com/kwebio/kweb-core/releases/tag/1.2.1) released with visibility change, should be available via MavenCentral in 30-60 minutes.

Would still appreciate it if you could elaborate on your use-case so I can think about a more robust solution, so I'll leave this open for now.

**Comment by chandrin94** [comment]
Thank you. 

Yes of course, i will elaborate. We persist the client ids on shutdown, so that the client reconnections can work through a backend restart when we reload them. For example, if authentication is used, it makes sure that the clients don't need to reauthenticate .

**Comment by sanity** [comment]
Interesting, will give this some thought but will close this issue for now. Thanks again :)

**Comment by chandrin94** [comment]
@sanity i think the clientState is still private in the 1.2.1 release.

**Comment by sanity** [comment]
Ugh, you're right - looks like I forgot to push local changes, will release a fix now.

**Comment by chandrin94** [comment]
No worries, happens to the best of us.

**Comment by sanity** [comment]
Ok, 1.2.2 released with a few minor dependency updates, it should be available from Maven Central within an hour.

I have a few more questions about what you're doing here but if it's ok I'll follow-up on this issue: #391
