### ISSUE TITLE
Can't remove/replace viewport meta "K_head"

### ISSUE THREAD

**Issue by alexpopa95** [kwebio/kweb-core#404]
Hello, I have a strange behavior in which I set my custom head viewport meta but there still is the default tag with `id="K_head"` (see screenshot below)

### My configuration
```kotlin
fun main() {
    Kweb(
        port = 8080,
        debug = false,
        plugins = listOf(
            StaticFilesPlugin(ResourceFolder("static"), "/static"),
            ViewportPlugin(),
            fomanticUIPlugin
        )
    ) {
        doc.head.new {
            // other head tags
            // I tried adding my meta here also, nothing changes
        }
        doc.body.new {
            // routing
        }
    }
}
```

### Screenshot
<img width="764" alt="meta_k_head" src="https://user-images.githubusercontent.com/11510670/205505187-18398081-9815-4acb-80d1-dbf428194d4c.png">

Is this behavior normal?

**Comment by Derek52** [comment]
Try 

```
doc.head {

}

doc.body {

}
```

**Comment by alexpopa95** [comment]
@Derek52 Thank you for the suggestion. Tried it but I have the same issue.

**Comment by sanity** [comment]
I think that's a bug, HtmlDocumentSupplier.createDocTemplate() is adding the first meta tag, which I don't think belongs there because that should be under the user's control. It's possible that I added this back in the early days.

Also, it's setting `<meta>`'s id to `K_head" which is already being used for the `<head>` element.

I think the fix is to remove that code so it's not appending the `<meta>`, but this may break people's pages so it will require a clear explanation in the release notes.

Thoughts?

**Comment by sanity** [comment]
This is the code that will be removed: https://github.com/kwebio/kweb-core/blob/432e9aeba243ac1b5f875bdcf53fa75cc55a9054/src/main/kotlin/kweb/html/HtmlDocumentSupplier.kt#L27-L30

**Comment by sanity** [comment]
Ok, 1.3.0 is out - hopefully it doesn't break a lot of people's websites but it shouldn't - from what I can tell the values it was using were the defaults anyway.

**Comment by alexpopa95** [comment]
Thank you @sanity.
I can confirm it is now working as expected.
I tried in various scenarios and without the meta tag the website behaves the same as before (in my case and I think in the case of others)

I would have an improvement to make for the ViewportPlugin.
Right now I am using a custom plugin similar to the one Kweb provides but with more customizations as this:
```kotlin
class ViewportPlugin(
    private val width: ViewportWidth = ViewportWidth.DeviceWidth,
    private val initialScale: Double = 1.0,
    private val maximumScale: Double = 1.0,
    private val userScalable: Boolean = false
) : KwebPlugin() {
    override fun decorate(doc: Document) {
        doc.head().appendElement("meta")
            .attr("name", "viewport")
            .attr(
                "content",
                "width=${width.text}" +
                        ", initial-scale=$initialScale" +
                        ", maximum-scale=$maximumScale" +
                        if (!userScalable) ", user-scalable=no" else ""
            )
    }
}
```

@sanity Do you think it could be done for the project? May help others needing these configurations. I could create a PR for it.

**Comment by sanity** [comment]
Yes, that would be great if you want to improve the ViewportPlugin - I'd be happy to merge a pull request.

**Comment by sanity** [comment]
Actually, I'm starting to wonder if a Viewport [component](https://docs.kweb.io/book/components.html) might be a better way to do this. I created this plugin before Kweb supported server-side rendering, so a plugin was the only option.

If you just want to stick with improving the plugin that's fine - but if you're interested in doing it as a component I think that would be a better solution for the long-term. Thoughts?
