### ISSUE TITLE
SSLConfig is deprecated, how to enable HTTPS?

### ISSUE THREAD

**Issue by markfarber** [kwebio/kweb-core#444]
Ref: https://docs.kweb.io/api/kweb-core/kweb.https/-s-s-l-config/index.html

**Comment by sanity** [comment]
Docs need to be updated, use [httpsConfig](https://docs.kweb.io/api/kweb-core/kweb/-kweb/index.html?query=class%20Kweb%20:%20Closeable) parameter of Kweb constructor.
