### ISSUE TITLE
Provide a convenient way to set page title

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#46]

**Comment by sanity** [comment]
This might end up getting folded into a broader rethink about how to make it easy to modify the contents of the page's <head>.

**Comment by sanity** [comment]
Actually, a simple approach would be:

```
Kweb() {
    doc.head.title = KVar("Title")
}
```

**Comment by Benjozork** [comment]
there should also be the option to not wrap the value in a `KVar` if the title is static, especially since `KVar` uses reflection

**Comment by sanity** [comment]
Hmm, perhaps I'm misunderstanding, but `KVar`s don't normally use reflection, except - for example - if created with `KVar.property` which does use reflection internally.

I'm not sure that using a `KVar` is going to be less efficient than using a `String` directly in the case that the value is set once and not modified.

Again, I may have misunderstood.

**Comment by Benjozork** [comment]
You're right, I misread the code.

I would still argue that there should be a way to set it without wrapping the value in `KVar`, simply for code readability reasons, but that's kinda nitpicking.

**Comment by sanity** [comment]
Yeah, I think in most cases the page title is likely going to change depending on the page URL, which will imply using a `KVar`, but I'll give it further thought.  Appreciate the suggestion.

**Comment by sne11ius** [comment]
This should also be integrated with routing, as one probably wants to change the title when navigating to a different route.

**Comment by sanity** [comment]
@sne11ius Something like this should currently work:

```kotlin
route {
  path("/about/{name}") { params ->
    val nameKV = params["name"]
    doc.head.title.text(nameKV.map { "Welcome $it!" })
  }
}
```

**Comment by sanity** [comment]
`doc.head.title.text("Page Title")` now works.
