### ISSUE TITLE
Table vs unordered list

### ISSUE THREAD

**Issue by ablaagaard** [kwebio/kweb-core#536]
I'm experimenting with kweb, and I'm a bit puzzled.
If I take the example:

val list = KVar(listOf("one", "two", "three"))

```
Kweb(port = 16097) {
    doc.body {
        render(list) { rList ->
            ul {
                for (item in rList) {
                    li().text(item)
                }
            }
        }
    }
}
```

This works, and I can update the list as described:

`list.value = listOf("four", "five", "six")
`
Now if I modify the example to render as table instead (I understand this is not efficient, but ignore that for now):

```
Kweb(port = 16097) {
    doc.body {
        render(list) { rList ->
            table {
                tr {
                   for (item in rList) {
                       td().text(item)
                   }
                }
            }
        }
    }
}
```

This still works, BUT if move the render call further in, it stops working (the first render works, but after the update it renders empty):

```
Kweb(port = 16097) {
    doc.body {
         table {
             tr {
                render(list) { rList ->
                      for (item in rList) {
                          td().text(item)
                      }
                }
            }
        }
    }
}
```

I don't know if this is a bug, or you can explain why the last code does not work as expected, so I can get a better understanding of what will work and why?

**Comment by sanity** [comment]
Hmm, that last one should work - I'll need to investigate. 

Note that [renderEach](https://docs.kweb.io/book/state.html#rendering-lists-with-rendereach) is a more efficient way to render lists.

Appreciate the bug report.
