### ISSUE TITLE
Implement true server-side rendering with rehydration of HTML document

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#57]
Currently Kweb supplies the initial page-building instructions in JavaScript, which works fine, but may have limitations for SEO, and may also delay page render time.

We should be able to use a library like https://jsoup.org to build the DOM in HTML in the initial page sent to the client, rather than as a sequence of JavaScript instructions.

This will touch a lot of the same code as #53, so while they're independent, it's worth being familiar with both before tackling either.

**Comment by sanity** [comment]
The counter-argument here might be that it won't actually make any difference, because modern search engines understand JavaScript.  I'm interested to hear other's opinions, for or against.

**Comment by sanity** [comment]
Sought and received useful feedback on this in two Reddit discussions:

* [r/kotlin](https://www.reddit.com/r/Kotlin/comments/c6vpbv/how_important_is_full_serverside_html_generation/)
* [r/webdev](https://www.reddit.com/r/webdev/comments/c7fdk6/how_important_is_it_full_serverside_html/)

**Comment by sanity** [comment]
This research appears highly relevant, and provides some useful terminology: https://developers.google.com/web/updates/2019/02/rendering-on-the-web

**Comment by sne11ius** [comment]
> The counter-argument here might be that it won't actually make any difference, because modern search engines understand JavaScript. I'm interested to hear other's opinions, for or against.

Last time I checked, most "search engines" didn't do any js at all. Keep in mind there is more than Google - it's all the places you can can use a link, like WhatsApp, Twitter and so on.

**Comment by sanity** [comment]
> Last time I checked, most "search engines" didn't do any js at all. Keep in mind there is more than Google - it's all the places you can can use a link, like WhatsApp, Twitter and so on.

To what extent could those use cases be addressed by adding [open graph](https://ogp.me/) tags to  the HTML document?

Regardless, I would still like to get SSR implemented in Kweb, the `onclick` issue mentioned above is the only part I'm unsure about.

**Comment by sne11ius** [comment]
> > Last time I checked, most "search engines" didn't do any js at all. Keep in mind there is more than Google - it's all the places you can can use a link, like WhatsApp, Twitter and so on.
> 
> To what extent could those use cases be addressed by adding [open graph](https://ogp.me/) tags to the HTML document?

As per the link, it's consumed by Google and Facebook. I'm sure providing these tags won't do anything in > 90% of the cases I care about.

Also keep in mind that these tags require a lot of work to be generated. There is about zero adoption of these "provide more meta data tags" approaches and personally, I consider them as failed.

**Comment by sanity** [comment]
Fair enough, that definitely lends weight to getting this feature implemented.

**Comment by sne11ius** [comment]
I think it comes down to where you primarily want the framework to be used. It's fine to serve a blank page with with just a big ball of js (CSR) for internal applications. For public facing websites, doing some form of SSR ist a must have - at least in my opinion ;)

**Comment by sanity** [comment]
FYI - preliminary version of this now works in this branch: https://github.com/kwebio/kweb-core/tree/issue-57-Implement_true_server-side_rendering_with_rehydration_of_HTML_document

**Comment by sanity** [comment]
Implemented in release 0.6.0 which should be available in the next few minutes.
