### ISSUE TITLE
Artifact jar name is unhelpful

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#62]
The current KWeb jar that is up on jitpack.io is named `core-0.4.18.jar`. This is a very unhelpful name and judging by the buildscripts, it looks (to me) also unintentional.

I thought it was just me, but apparently the [logs also confirm it](https://jitpack.io/com/github/kwebio/core/0.4.18/build.log):
```
Build artifacts:
com.github.kwebio:core:0.4.18

Files: 
com/github/kwebio/core/0.4.18
com/github/kwebio/core/0.4.18/build.log
com/github/kwebio/core/0.4.18/core-0.4.18-javadoc.jar
com/github/kwebio/core/0.4.18/core-0.4.18-sources.jar
com/github/kwebio/core/0.4.18/core-0.4.18.jar
com/github/kwebio/core/0.4.18/core-0.4.18.pom
com/github/kwebio/core/0.4.18/core-0.4.18.pom.md5
com/github/kwebio/core/0.4.18/core-0.4.18.pom.sha1
```

**Comment by sanity** [comment]
Ah, good point - would 'kweb-core' be better?

**Comment by sanity** [comment]
Oh, I think the issue with Jitpack is that it takes the jar name from the github project name, although that can probably be overridden.

What would be better, `kweb-core`?

**Comment by sanity** [comment]
Oh, parallel question, out of curiosity - why do you need to deal with the jar directly?

**Comment by alkoclick** [comment]
kweb-core would be pretty good, yes!

> Oh, parallel question, out of curiosity - why do you need to deal with the jar directly?

A) Due to the auto generated module system name, I have to actually put 
```java
requires core.master.snapshot
```
in my module-info.java file, which I'm sure you'll agree is highly... problematic.

B) For some exceptions, several dev-ops issues etc, you'll often see the offending jar's name. You will eventually find what this jar is and what it contains, it's just not immediately obvious (and you even run the risk of classpath collisions in the fairly reasonable case that anybody else is publishing _core-VERSION.jar_ artifacts

**Comment by alkoclick** [comment]
It's not a huge issue, but it is something that should be easy to fix and can only have positive results :)

**Comment by sanity** [comment]
The easiest way might actually be to rename the repository, IIRC Github does a good job of setting up redirects so the disruption should be fairly minimal.

**Comment by ethanmdavidson** [comment]
I second renaming the repo to "kweb-core" or even just "kweb". Another added benefit is getting a better default directory name when you do git clone. Also, seems to be the standard way to do things when the organization name is the same as the project name, e.g:

- https://github.com/ktorio/ktor
- https://github.com/grails/grails-core
- https://github.com/liquibase/liquibase
- https://github.com/dropwizard/dropwizard

**Comment by sanity** [comment]
Ok guys, I've renamed `core` to `kweb-core` and `docs` to `kweb-docs` - I think I've updated the necessary links although Github should redirect from the old repo.

Please play around and let me know if you notice any issues.

**Comment by ethanmdavidson** [comment]
Looks good. I've updated all the links in kweb-docs. Only thing I'm seeing is that on https://docs.kweb.io the "Edit on Github" buttons are still pointing to the old url (e.g. https://github.com/kwebio/docs/blob/master/index.rst instead of https://github.com/kwebio/kweb-docs/blob/master/index.rst) but I'm not sure how those are set up.

**Comment by sanity** [comment]
@ethanmdavidson Thanks, I think I've fixed that now.

**Comment by sanity** [comment]
Going to close this as I think it's done, please reopen if there are any issues.
