### ISSUE TITLE
Fomantic UI plugin should include js and css rather than referencing a CDN

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#66]

**Comment by rpanic** [comment]
I think this could be easily done by using the StaticFilesPlugin. I tested it already, it would work, but is that the way you intended it to work?

**Comment by sanity** [comment]
I think if the StaticFilesPlugin can be extended to support loading files from a resource rather than from the filesystem, then we could use that, yes.

Note that there is also a plugin dependency mechanism implemented [here](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/io/kweb/Kweb.kt#L273).

**Comment by sanity** [comment]
@rpanic I'm experiencing some issues with the current master branch, getting this error:

```Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:5467/projects/Adzzan/kweb_native_assets/jquery/jquery-3.1.1.min.js' with computed SHA-256 integrity 'oysslRmT++cDML9iYUttRMB5bOZgzr4zho6DtSIMm1Q='. The resource has been blocked.```

Also, it seems to be serving up the HTML bootstrap file rather than `semantic.min.js`, any ideas?

I might need to back out this change temporarily :(

**Comment by sanity** [comment]
Unfortunately I had to revert this again in 0.5.9 - it seemed like it was serving up a HTML file rather than the Fomantic JavaScript it was expecting.  I thought I had verified this but it seems that my browser might have been caching something.

Couldn't dig deeper just now as I'm tied up with another project.

**Comment by sanity** [comment]
This is now implemented and seems to be working fine.
