### ISSUE TITLE
Properties missing in code but present in documentation

### ISSUE THREAD

**Issue by hannespernpeintner** [kwebio/kweb-core#82]
Hi,

I'm test diving into your framework, I saw that there are some properties documented in the source code doc that aren't present in the code, for example a hot reload feature.

https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/io/kweb/Kweb.kt#L53

Cheers :)

**Comment by sanity** [comment]
Ah, yes - thank you.  That was supported in the past and may be supported again, I should remove references to it in the API unless/until it can be replaced.
