### ISSUE TITLE
How to handle static content?

### ISSUE THREAD

**Issue by hannespernpeintner** [kwebio/kweb-core#83]
Hi again,

I'm currently prototyping a small web application which is a port of an angular app. Therefore, I have a lot of existing resources like css. Some of them, I can easily load as a resource and embed them into the page. Some others however, contain references to other files that are included and reused elsewhere. For example with "url(...)" calls in css files. I can't find a way to server static content at all with Kweb, is this impossible?? I took a look at the Kweb class and it looks like it would be fairly easy to implement this feature by accepting an array of static resources as strings in Kweb and passing it into the "static" part of the ktor routing, just like one would do it with ktor directly. 

It would be really helpful to have this feature, don't you think? :)

Thx

**Comment by rpanic** [comment]
Hi,

actually this feature exists since I made this pull request 
https://github.com/kwebio/kweb-core/pull/78
and extended it a bit in
https://github.com/kwebio/kweb-core/pull/80

You can use this as a Plugin. If you don´t know how the plugin mechanism works, the docs describe it pretty good, or just ask :)

**Comment by hannespernpeintner** [comment]
Thanks, will take a look into it as soon as i can!

**Comment by hannespernpeintner** [comment]
Okay, works like a charm, that's good. Is it possible to serve static files from resources somehow??

**Comment by rpanic** [comment]
Perfect, yes, you can use the second constructor with the `Resource` object. That indicated the path in the resources

**Comment by hannespernpeintner** [comment]
Uuuhm, okay I saw that and didn't dig deeper into the plugin itself - does it work with running the main method from the IDE? I have a standard resources layout and it seem to not generate the paths in a way that intellij run main method works.

**Comment by hannespernpeintner** [comment]
Any help here? :) small example would be helpful :)

**Comment by sanity** [comment]
@rpanic Ping?

**Comment by rpanic** [comment]
Sorry for the late reply.
Well, you have to use it with the Kweb Plugin mechanism. 
A example of that with some files in the `src/main/resources/test/` folder.

`Kweb(8080, plugins = listOf(fomanticUIPlugin, StaticFilesPlugin(ResourceFolder("testfolder"))
            )){`

When doing that, it should automatically serve the files in that folder with the /assets/ route. That is by default, you can change that with the second parameter.

So you can reach the testfile.txt, which is in the folder mentioned above, like this:

`http://localhost/assets/testfile.txt`

Btw, if you want to use the resource folder as the root for static files, just replace `"testfolder"` with an empty string

**Comment by hannespernpeintner** [comment]
Works! Seems I got confused by my IDE or forgot to restart somehow. Thanks for your support, really appreciated.
