### ISSUE TITLE
Rendering a table

### ISSUE THREAD

**Issue by GenerRR** [kwebio/kweb-core#86]
Hi, sorry for the very newbie question, but what is the proper way to show dynamic objects like MutableList, which contains changing number of data class elements,

            render(listOfObjects) { rList ->
                ul().new {
                    for (item in rList) {
                        li().text("${item.param1} ${item.param2}")
                    }
                }
            }

looks like what i need, and it works, but is there any way to build it with fomantic style table , with different parameters in different cells, etc ?

**Comment by GenerRR** [comment]
Hi, sorry for the very newbie question, but what is the proper way to show dynamic objects like MutableList, which contains changing number of data class elements,
```
            render(listOfObjects) { rList ->
                ul().new {
                    for (item in rList) {
                        li().text("${item.param1} ${item.param2}")
                    }
                }
            }
```
looks like what i need, and it works, but is there any way to build it with fomatic style table , with different parameters in different cells, etc ?

**Comment by sanity** [comment]
Your approach will work although it will re-render the entire `<ul>` every time the list or an item in it changes.

Take a look at [renderEach](https://github.com/kwebio/kweb-core/blob/b9593970f2d58a63e59054c29f83a38d22f9d128/src/main/kotlin/io/kweb/demos/todo/TodoApp.kt#L136), although it needs an [OrderedViewSet](https://github.com/kwebio/shoebox/blob/master/src/main/kotlin/io/kweb/shoebox/OrderedViewSet.kt) which must be retrieved from a [Shoebox](https://github.com/kwebio/shoebox).

To render it as a Fomantic-style table using `render`, just be sure to add the Fomantic plugin when you create your `Kweb` object, and then use the appropriate classes, mirroring the [fomantic documentation](https://semantic-ui.com/collections/table.html), something like:

```kotlin
render(listOfObjects) { rList ->
  table(fomantic.ui.celled.table).new {
    thead().new {
       ...
    }
    tbody().new {
       for ((ix, item) in rList.withIndex()) {
          tr().new {
            td().setAttributeRaw("data-label", "Name").text(item)
          }
        }
    }
  }
}
```
Or, to avoid a re-render every time an item changes:

```kotlin
render(listOfObjects.indices) { indices ->
  table(fomantic.ui.celled.table).new {
    thead().new {
       ...
    }
    tbody().new {
       for (itemIx in indices) {
          tr().new {
            td().setAttributeRaw("data-label", "Name").text(listOfObjects[itemIx]) // <-- works due to [this extension function](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/io/kweb/state/KVarExtensions.kt#L5).
          }
        }
    }
  }
}
```

Does that answer your question?

**Comment by GenerRR** [comment]
Yes, it works, thank you!

**Comment by sanity** [comment]
Oh, you might also find this relevant https://github.com/kwebio/kweb-core/tree/master/src/main/kotlin/io/kweb/plugins/tablesort
