### ISSUE TITLE
Document how to autoreload pages on code changes while in debug mode

### ISSUE THREAD

**Issue by stangls** [kwebio/kweb-core#88]
When running my KWeb application in debug mode from the IDE, I would like to have the browser reload the page when there are code changes.

**Comment by sanity** [comment]
I got this working a while back using [DCEVM](https://dcevm.github.io/), however I wasn't really using it and so I removed it until I could spend time on it.

You can find the original code [here](https://github.com/kwebio/kweb-core/commits/fa2080df056919fb36e5df9c7bcf482e0b988484/src/main/kotlin/io/kweb/dev), it shouldn't be too difficult to add it back into the current master branch if anyone would like to take a stab at it.

**Comment by sanity** [comment]
I was looking for this and eventually found it, it was the old documentation for the code I mentioned before: https://kweb.io/use/live-coding.html

**Comment by alkoclick** [comment]
It's probably much easier to use Ktor's [autoreload](https://ktor.io/servers/autoreload.html) and depending on your build tool, some variation of the watch/compile commands. The Ktor page provides documentation on how to do it in Gradle and IDEA

**Comment by stangls** [comment]
Thanks, I found appropriate solution in Ktor.

**Comment by kernitus** [comment]
Hey @alkoclick how did you get Ktor's autoreload to work? I can't seem to get gradle either to autobuild not autoreload the webpage using the tutorial you linked!

**Comment by alkoclick** [comment]
Sorry @kernitus don't remember much anymore :/ I do remember that I also had trouble implementing it, and when I finally did it, the solution was pretty flaky, so I ended up dropping it. Sorry for the delay!

**Comment by sanity** [comment]
Should verify that Ktor's [autoreload](https://ktor.io/docs/auto-reload.html) works with Kweb, and document its use.

**Comment by sanity** [comment]
# Modified issue

Should verify that Ktor's [autoreload](https://ktor.io/docs/auto-reload.html) works with Kweb, and document its use.
