### ISSUE TITLE
Code inside the Kweb block doesn't produce error messages

### ISSUE THREAD

**Issue by PotatoCurry** [kwebio/kweb-core#89]
For some reason, I don't get any error messages from code executed inside the Kweb block, even if something has very clearly gone wrong.

For example, this code produces an error (as it should).
```kotlin
fun main() {
    val port = 8080 // System.getenv("PORT").toInt()
    val a = 8 / 0
    Kweb(port) {
        // Application code
    }
}
```
```
Exception in thread "main" java.lang.ArithmeticException: / by zero
    at io.github.potatocurry.borebox.MainKt.main(Main.kt:29)
    at io.github.potatocurry.borebox.MainKt.main(Main.kt)

Process finished with exit code 1
```

While this code produces no error besides the logger warning.
```kotlin
fun main() {
    val port = 8080 // System.getenv("PORT").toInt()
    Kweb(port) {
        val a = 8 / 0
        // Application code
    }
}
```
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
Trying to visit localhost:8080 in the browser returns a blank screen, presumably because of the unhandled (yet invisible) exception; no errors appear to be logged to the console.

**Comment by sanity** [comment]
Hmm, this may be a regression - just to confirm, what version of Kweb are you using?

**Comment by PotatoCurry** [comment]
0.5.10, I started working on this project just a few days ago.

**Comment by sanity** [comment]
Ah, turns out that SLF4J message might be the problem, could you try adding this to your `build.gradle` dependencies block and let me know if it helps?

```groovy
compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.30'
```

**Comment by PotatoCurry** [comment]
Thank you, that fixed the issue.

**Comment by sanity** [comment]
Great, I'll add a note to the documentation.
