### ISSUE TITLE
Query parameters are not included in "history.pushState"

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#91]
Issue summary: When the query parameters of a url are modified, the WebBrowser pushes an identical state to the history. This is because it only pushes the path changes.

Use case:
I have a form with a few fields. When the user clicks search I want to
A) Fetch some items and display them in a table underneath
B) Update the query params
C) Push the change to history, as the user can click on any table item and navigate away

Cause:
```kotlin
    // Note: It's important that we only have one KVar for the URL for this WebBrowser to ensure that changes
    //       propagate everywhere they should.  That's why it's lazy.
    val url: KVar<String>
            by lazy {
                val url = KVar(httpRequestInfo.requestedUrl)

                url.addListener { _, newState ->
                    pushState(newState)
                }

                url
            }

    fun pushState(path: String) {
        val url = URL.parse(path)
        execute("""
>>>     history.pushState({}, "", location.origin+"${url.path()}");
        """.trimIndent())
    }
```

(Line ref for quick access)
https://github.com/kwebio/kweb-core/blob/e719f98d7d290196c1adaae7721fe47871d32d66/src/main/kotlin/io/kweb/WebBrowser.kt#L97

Suggested fix: Use the full value of the java url [See pull request]()

Potential perils: 
* The previous implementations was pushing only the relative path (and grabbing the base from javascript), while this is proposing pushing the full updated URL. 
* Potential injection point with using the value of `URL.toString()`? I would expect java to be smart enough though

**Comment by sanity** [comment]
0.5.12 released with this fix, thank you :)

**Comment by alkoclick** [comment]
Awesome, thanks!
