### ISSUE TITLE
Allow access to Gson type casting for `browser.evaluate` response

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#95]
Basically, now that https://github.com/kwebio/kweb-core/issues/93 is fixed, it would be a nice API improvement to be able to use generics right up until the point where GSON casts the response to a JVM object, to be able to avoid getting the object through multiple castings and to specify some potential custom javascript return types.

Element currently has this:
```kotlin
    /**
     * Evaluate some JavaScript in the browser and return the result via a Future.
     * This the foundation upon which most DOM-querying functions in this class
     * are based.
     */
    fun <O> evaluate(js: String, outputMapper: (Any) -> O): CompletableFuture<O>? {
        return browser.evaluate(js).thenApply(outputMapper)
    }
```
which is pretty close, but still first gets the response as `Any` rather than <T>

This is a fairly nitpicky issue, with some minor API gain, but would be a nice to have if it's not too much trouble

**Comment by alkoclick** [comment]
Potentially related to #59

**Comment by sanity** [comment]
Working on it in this here: https://github.com/kwebio/kweb-core/pull/96

**Comment by sanity** [comment]
Completed a while ago.
